version: 2
updates:
  # Rust dependencies
  - package-ecosystem: cargo
    directory: "/quickwit"
    schedule:
      interval: "monthly"
    groups:
      arrow-datafusion:
        applies-to: version-updates
        patterns:
          - "arrow"
          - "datafusion"
          - "datafusion-*"
          - "object_store"
          - "parquet"
          - "thrift"
      aws:
        applies-to: version-updates
        patterns:
          - "aws-*"
      google-cloud:
        applies-to: version-updates
        patterns:
          - "google-cloud-*"
      reqwest:
        applies-to: version-updates
        patterns:
          - "reqwest"
          - "reqwest-*"
      rust-security:
        applies-to: security-updates
        patterns:
          - "*"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    cooldown:
      default-days: 2

  # Docker dependencies
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 2

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 2

  # NPM dependencies
  - package-ecosystem: npm
    directory: "/quickwit/quickwit-ui"
    schedule:
      interval: "monthly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 2
