variables:
  BAZEL_CI_IMAGE: registry.ddbuild.io/bazel:5
  DOCKER_CI_IMAGE: registry.ddbuild.io/docker:27.3.1

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

default:
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ddbuild.io/DataDog/".insteadOf "https://github.com/DataDog/"

stages:
  - build
  - publish
  - sign
  - deploy

build_docker_image:
  image: $DOCKER_CI_IMAGE
  stage: build
  tags:
    - arch:arm64
  rules:
    - changes:
        - .gitlab-ci.yml
        - quickwit/**
  script:
    - scripts/image-tool.sh --build --push --metadata-file meta.json
  artifacts:
    paths:
      - meta.json

publish_to_public_docker_registries:
  stage: publish
  trigger:
    project: DataDog/public-images
    branch: main
    strategy: depend
  variables:
    IMG_SOURCES: registry.ddbuild.io/pomsky:edge
    IMG_DESTINATIONS: cloudprem:edge
    IMG_REGISTRIES: dockerhub

sign_docker_image:
  image: $DOCKER_CI_IMAGE
  stage: sign
  needs:
    - build_docker_image
  id_tokens:
    DDSIGN_ID_TOKEN:
      aud: image-integrity
  script:
    - scripts/image-tool.sh --sign --metadata-file meta.json

deploy_to_staging:
  image: $BAZEL_CI_IMAGE
  stage: deploy
  tags:
    - arch:amd64
  script:
    - export PATH="$PATH:$CI_PROJECT_DIR/bazel-bin"
    - bzl run staging.publish
