variables:
  BAZEL_CI_IMAGE: registry.ddbuild.io/bazel:5

stages:
  - publish

publish-workflow:
  image: $BAZEL_CI_IMAGE
  stage: publish
  tags: ["runner:main"]
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ddbuild.io/DataDog/".insteadOf "https://github.com/DataDog/"
  script:
    - bzl run pomsky-workflow.publish
