npmRegistryServer: "https://depot-read-api-npm.us1.ddbuild.io/internal/magicmirror/magicmirror"
enableNetwork: true
networkSettings:
  "registry.npmjs.org":
    httpProxy: "http://0.0.0.0"
    httpsProxy: "http://0.0.0.0"
