id: azure
metric_id: azure
backend_only: false
installation_sources:
  - azure
  - azure.alertsmanagement
  - azure.analysisservices
  - azure.apiconfiguration
  - azure.apimanagement
  - azure.authorization
  - azure.automation
  - azure.batchai
  - azure.batch
  - azure.blockchain
  - azure.cache
  - azure.cdn
  - azure.classiccompute
  - azure.classicstorage
  - azure.cognitiveservices
  - azure.containerinstance
  - azure.containerregistry
  - azure.datafactory
  - azure.datalakestore
  - azure.dbformariadb
  - azure.dbformysql
  - azure.devices
  - azure.documentdb
  - azure.enterpriseknowledgegraph
  - azure.eventgrid
  - azure.eventhub
  - azure.hdinsight
  - azure.insights
  - azure.iotcentral
  - azure.keyvault
  - azure.kusto
  - azure.logic
  - azure.machinelearningservices
  - azure.managedidentity
  - azure.operationalinsights
  - azure.operationsmanagement
  - azure.peering
  - azure.relay
  - azure.resourcegroup
  - azure.resources
  - azure.search
  - azure.security
  - azure.servicebus
  - azure.servicefabric
  - azure.streamanalytics
  - azure.subscription
  - azure.synapse
# these sources are excluded from the main azure pipeline and are in their own since they handle some facets differently:
# azure.network: has message-remapper
# azure.compute: has message-remapper
# azure.web and azure.storage - already existed so left as-is
# azure.activedirectory
# azure.containerservice - parsers and facets related to AKS logs like event severity, reason and message
# azure.sql
facets:
  - facetType: range
    groups:
      - Measure
    name: Duration
    path: duration
    source: log
    type: double
    unit:
      family: time
      name: nanosecond
  - groups:
      - Event
    name: Event Name
    path: evt.name
    source: log
  - groups:
      - Event
    name: Event Outcome
    path: evt.outcome
    source: log
  - groups:
      - Web Access
    name: Client IP
    path: network.client.ip
    source: log
  - groups:
      - User
    name: User ID
    path: usr.id
    source: log
  - groups:
      - Event
    name: Event Category
    path: evt.category
    source: log
  - groups:
      - Azure
    name: Resource ID
    path: resourceId
    source: log
    type: string
  - groups:
      - Azure
    name: Resource Name
    path: resource_name
    source: log
    type: string
  - groups:
      - Azure
    name: Correlation ID
    path: correlationId
    source: log
    type: string
  - groups:
      - Azure
    name: Subscription ID
    path: subscription_id
    source: tag
    type: string
  - groups:
      - Azure
    name: Resource Group
    path: resource_group
    source: tag
    type: string
pipeline:
  type: pipeline
  name: Azure
  enabled: true
  filter:
    query: source:(azure OR azure.alertsmanagement OR azure.analysisservices OR azure.apiconfiguration OR azure.apimanagement OR azure.authorization OR azure.automation OR azure.batchai OR azure.batch OR azure.blockchain OR azure.cache OR azure.cdn OR azure.classiccompute OR azure.classicstorage OR azure.cognitiveservices OR azure.containerinstance OR azure.containerregistry OR azure.datafactory OR azure.datalakestore OR azure.dbformariadb OR azure.dbformysql OR azure.devices OR azure.documentdb OR azure.enterpriseknowledgegraph OR azure.eventgrid OR azure.eventhub OR azure.hdinsight OR azure.insights OR azure.iotcentral OR azure.keyvault OR azure.kusto OR azure.logic OR azure.machinelearningservices OR azure.managedidentity OR azure.operationalinsights OR azure.operationsmanagement OR azure.peering OR azure.relay OR azure.resourcegroup OR azure.resources OR azure.search OR azure.security OR azure.servicebus OR azure.servicefabric OR azure.streamanalytics OR azure.subscription OR azure.synapse)
  processors:
    - type: grok-parser
      name: Parsing `resource_name` from `resourceId`
      enabled: true
      source: resourceId
      samples:
        - /SUBSCRIPTIONS/8C56D827-5F07-45CE-8F2B-6C5001DB5C6F/RESOURCEGROUPS/ET-COMPUTE-RG/PROVIDERS/MICROSOFT.STORAGE/STORAGEACCOUNTS/ETFLOWLOGS
      grok:
        supportRules: |
          _non_extracted_resource %{regex("[a-zA-Z0-9-_.]*")}
          _resource_name %{regex("[a-zA-Z0-9-_.]*"):resource_name:lowercase}
          _subscriptions %{regex("(?i)SUBSCRIPTIONS")}
          _resource_groups %{regex("(?i)RESOURCEGROUPS")}
          _providers %{regex("(?i)PROVIDERS")}
        matchRules: |
          extract_resource_name /%{_subscriptions}\/%{_non_extracted_resource}\/%{_resource_groups}\/%{_non_extracted_resource}\/%{_providers}%{_non_extracted_resource}\/%{_non_extracted_resource}\/%{data}\/%{_resource_name}
    - type: date-remapper
      name: Define `time` as the official date of the log
      enabled: true
      sources:
        - time
    - type: status-remapper
      name: Define `level` as the official status of the log
      enabled: true
      sources:
        - level
    - type: attribute-remapper
      name: Map `category` to `evt.category`
      enabled: true
      sources:
        - category
      target: evt.category
      preserveSource: false
      overrideOnConflict: false
      sourceType: attribute
      targetType: attribute
    - type: attribute-remapper
      name: Map `operationName` to `evt.name`
      enabled: true
      sources:
        - operationName
      target: evt.name
      preserveSource: false
      overrideOnConflict: false
      sourceType: attribute
      targetType: attribute
    - type: attribute-remapper
      name: Map `resultType` to `evt.outcome`
      enabled: true
      sources:
        - resultType
      target: evt.outcome
      targetFormat: string
      preserveSource: false
      overrideOnConflict: false
      sourceType: attribute
      targetType: attribute
    - type: attribute-remapper
      name: Map `callerIpAddress` to `network.client.ip`
      enabled: true
      sources:
        - callerIpAddress
      target: network.client.ip
      preserveSource: false
      overrideOnConflict: false
      sourceType: attribute
      targetType: attribute
    - type: arithmetic-processor
      name: Compute duration in nanoseconds from durationMs in miliseconds
      enabled: true
      expression: durationMs * 1000000
      target: duration
      replaceMissing: false
    - type: attribute-remapper
      name: Map `identity.authorization.evidence.principalId` to `usr.id`
      enabled: true
      sources:
        - identity.authorization.evidence.principalId
      target: usr.id
      preserveSource: false
      overrideOnConflict: false
      sourceType: attribute
      targetType: attribute
