id: elb
metric_id: amazon-elb
backend_only: false
facets:
  - facetType: range
    groups:
      - Measure
    name: Duration
    path: duration
    source: log
    type: double
    unit:
      family: time
      name: nanosecond
  - groups:
      - Web Access
    name: Method
    path: http.method
    source: log
  - groups:
      - Web Access
    name: Referer
    path: http.referer
    source: log
  - groups:
      - Web Access
    name: Status Code
    path: http.status_code
    source: log
  - groups:
      - Web Access
    name: URL Host
    path: http.url_details.host
    source: log
  - groups:
      - Web Access
    name: URL Path
    path: http.url_details.path
    source: log
  - groups:
      - Web Access
    name: URL Port
    path: http.url_details.port
    source: log
  - groups:
      - Web Access
    name: URL scheme
    path: http.url_details.scheme
    source: log
  - groups:
      - Web Access
    name: Browser
    path: http.useragent_details.browser.family
    source: log
  - groups:
      - Web Access
    name: Device
    path: http.useragent_details.device.family
    source: log
  - groups:
      - Web Access
    name: OS
    path: http.useragent_details.os.family
    source: log
  - groups:
      - Web Access
    name: Client IP
    path: network.client.ip
    source: log
  - groups:
      - AWS
    name: ELB Name
    path: elb.name
    source: log
  - groups:
      - AWS
    name: S3 Bucket
    path: aws.s3.bucket
    source: log
    type: string
pipeline:
  type: pipeline
  name: AWS ELB Access
  enabled: true
  filter:
    query: source:elb
  processors:
    - type: grok-parser
      name: Parsing ELB access logs
      enabled: true
      source: message
      samples:
        - 2015-05-13T23:39:43.945958Z my-loadbalancer 192.168.131.39:2817 10.0.0.1:80 0.000073 0.001048 0.000057 200 200 0 29 "GET http://www.example.com:80/ HTTP/1.1" "curl/7.38.0" - -
        - 2015-05-13T23:39:43.945958Z my-loadbalancer 192.168.131.39:2817 10.0.0.1:80 0.000086 0.001048 0.001337 200 200 0 57 "GET https://www.example.com:443/ HTTP/1.1" "curl/7.38.0" DHE-RSA-AES128-SHA TLSv1.2
        - 2015-05-13T23:39:43.945958Z my-loadbalancer 192.168.131.39:2817 10.0.0.1:80 0.001069 0.000028 0.000041 - - 82 305 "- - - " "-" - -
        - 2015-05-13T23:39:43.945958Z my-loadbalancer 192.168.131.39:2817 10.0.0.1:80 0.001065 0.000015 0.000023 - - 57 502 "- - - " "-" ECDHE-ECDSA-AES128-GCM-SHA256 TLSv1.2
      grok:
        supportRules: |
          _elb_name %{notSpace:elb.name}
          _http_protocol %{word:http.protocol}
          _backend_status_code %{integer:elb.backend_status_code}
          _request_processing_time %{number:elb.performance.request_processing_time:scale(1000)}
          _backend_processing_time %{number:elb.performance.backend_processing_time:scale(1000)}
          _reponse_processing_time %{number:elb.performance.response_processing_time:scale(1000)}
          _ssl_cipher %{notSpace:http.ssl.cipher:nullIf("-")}
          _ssl_protocol %{notSpace:http.ssl.protocol:nullIf("-")}
          _bytes_written %{integer:network.bytes_written}
          _bytes_read %{integer:network.bytes_read}
          _client_ip %{ipOrHost:network.client.ip}
          _client_port %{integer:network.client.port}
          _destination_ip %{ipOrHost:network.destination.ip}
          _destination_port %{integer:network.destination.port}
          _duration %{number:duration:scale(1000000)}
          _version HTTP\/%{regex("\\d+\\.\\d+"):http.version}
          _url %{notSpace:http.url:nullIf("-")}
          _user_agent %{regex("[^\\\"]*"):http.useragent:nullIf("-")}
          _status_code %{integer:http.status_code}
          _method %{word:http.method}
          _date_access %{date("yyyy-MM-dd'T'HH:mm:ss.SSSSSSZ"):date_access}
          _arn %{notSpace:aws.arn}
          _requestID "Root\=%{notSpace:TraceId}"
        matchRules: |
          elb.http %{_date_access} %{_elb_name}\s+(?:%{_client_ip}:%{_client_port}|-) (?:%{_destination_ip}:%{_destination_port}|-) (?>-1|%{_request_processing_time}) (?>-1|%{_backend_processing_time}) (?>-1|%{_reponse_processing_time}) (?:%{_status_code}|-) (?:%{_backend_status_code}|-) %{_bytes_read} %{_bytes_written}\s+"(?>%{_method} |- )%{_url}(?> %{_version}| -\s*)" "%{_user_agent}" %{_ssl_cipher} %{_ssl_protocol}( %{_arn} %{_requestID})?

          alb %{_http_protocol} %{elb.http}.*
    - type: user-agent-parser
      name: ''
      enabled: true
      sources:
        - http.useragent
      target: http.useragent_details
      encoded: false
    - type: url-parser
      name: ''
      enabled: true
      sources:
        - http.url
      target: http.url_details
    - type: date-remapper
      name: Define `date_access` as the official date of the log
      enabled: true
      sources:
        - date_access
    - type: category-processor
      name: Categorise status code
      enabled: true
      categories:
        - filter:
            query: '@http.status_code:[200 TO 299]'
          name: OK
        - filter:
            query: '@http.status_code:[300 TO 399]'
          name: notice
        - filter:
            query: '@http.status_code:[400 TO 499]'
          name: warning
        - filter:
            query: '@http.status_code:[500 TO 599]'
          name: error
      target: http.status_category
    - type: arithmetic-processor
      name: Calculate request response time
      enabled: true
      expression: (elb.performance.request_processing_time + elb.performance.backend_processing_time + elb.performance.response_processing_time)*1000000
      target: duration
      replaceMissing: false
    - type: status-remapper
      name: Define `http.status_category` as the official status of the log
      enabled: true
      sources:
        - http.status_category
