image:
  repository: 727006795293.dkr.ecr.us-east-1.amazonaws.com/pomsky
  tag: edge
  pullPolicy: Always

podAnnotations:
  ad.datadoghq.com/pomsky.checks: |
      {
        "openmetrics": {
          "instances": [
            {
              "openmetrics_endpoint": "http://%%host%%:7280/metrics",
              "namespace": "cloudprem",
              "metrics": [".*"]
            }
          ]
        }
      }
  emissary.datadoghq.com/inject-lifecycle: "inject"

tolerations:
  - key: node
    operator: Equal
    effect: NoSchedule
    value: nodeless

  - key: cpu_arch
    operator: Equal
    effect: NoSchedule
    value: arm64

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: "node-role.kubernetes.io/nodeless"
            operator: Exists
          - key: "node.datadoghq.com/cpu_arch"
            operator: In
            values:
              - arm64

metastore:
  replicaCount: 1

  resources:
    limits:
      cpu: "500m"
      memory: "128Mi"
    requests:
      cpu: "500m"
      memory: "128Mi"

control_plane:
  resources:
    limits:
      cpu: "500m"
      memory: "128Mi"
    requests:
      cpu: "500m"
      memory: "128Mi"

indexer:
  replicaCount: 1

  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "1"
      memory: "1Gi"

searcher:
  replicaCount: 1

  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "1"
      memory: "1Gi"

janitor:
  resources:
    limits:
      cpu: "500m"
      memory: "128Mi"
    requests:
      cpu: "500m"
      memory: "128Mi"

config:
  metastore_uri: s3://logs-cloudprem-staging/indexes
  default_index_root_uri: s3://logs-cloudprem-staging/metastore
