version: 0.8

template_id: cloudprem

index_id_patterns:
  - cloudprem*

description: Index config template for the cloudprem indexes

priority: 0

indexing_settings:
  commit_timeout_secs: 5

# Note: replace ALL default tokenizer with ddg tokenizer
# There would be two tokenizers: ddg and ddg_ignore_case (for message and all)

# There is an additional truncation in fields that applies only to indexed logs: the value is truncated to 75 KiB for the message field and 25 KiB for non-message fields. 
# Datadog still stores the full text, and it remains visible in regular list queries in the Logs Explorer. However, the truncated version will be displayed when performing 
# a grouped query, such as when grouping logs by that truncated field or performing similar operations that display that specific field.
# => FF tokenizer truncation after 75Kb for message and 25Kb for other fields (seems quite high)

# Sources: 
# https://datadoghq.atlassian.net/wiki/spaces/LB/pages/2484928615/Logs+payload+format
# https://github.com/DataDog/logs-backend/blob/prod/domains/event-platform/libs/percolation/src/main/resources/elasticsearch/mappings/event.conf
# https://github.com/DataDog/logs-backend/blob/prod/domains/event-platform/libs/percolation/src/main/resources/elasticsearch/mappings/_root_event.conf
# Note that not all fields in event.conf and _root_event.conf are handled here yet

doc_mapping:
  mode: dynamic # To include `custom` attributes
  dynamic_mapping:  
    indexed: true  
    stored: true  
    tokenizer: default 
    record: position # for phrase queries
    fast: true # for range queries
  field_mappings:
    - name: timestamp # RFC3339
      type: datetime
      fast: true

    - name: message
      type: text
      tokenizer: default # +lowercase case insensitive search on message
      record: position
      fast: true

    - name: tags
      type: json # Best format to store tags is unclear
      tokenizer: default  
      record: position
      fast: true # for range queries
    
    # The subfiels are `message` and `stack`. Are there others?
    # If all fields are clear, we can convert to object.
    - name: error
      type: json 
      tokenizer: default
      record: position
      fast: true

    # other text like core attributes
    - name: service
      type: text
      tokenizer: default  
      record: position # for phrase search
      fast: true
    - name: service_type 
      type: text
      tokenizer: default  
      record: position # for phrase search
      fast: true
    - name: status
      type: text
      tokenizer: default  
      record: position # for phrase search
      fast: true
    - name: host
      type: text
      tokenizer: default  
      record: position # for phrase search
      fast: true
    - name: trace_id
      type: text
      tokenizer: default  
      record: position # for phrase search
      fast: true
    - name: span_id
      type: text
      tokenizer: default  
      record: position # for phrase search
      fast: true

   # TODO: normally there is an `sds_info` object. Check OP SDS scanner:
   # https://docs.datadoghq.com/observability_pipelines/processors/sensitive_data_scanner

    # default fields to search. 
    - name: default 
      type: concatenate
      concatenate_fields:
      - message
      - error
      tokenizer: 
      record: position # for phrase queries
      
    - name: all # ALL fields for *:search
      type: concatenate
      concatenate_fields: # This should contain all fields above
      # - timestamp # Not supported in concat fields
      - message
      - tags
      - error
      - service
      - service_type
      - status
      - host
      - trace_id
      - span_id
      include_dynamic_fields: true
      tokenizer: default # +lowercase insensitive
      record: position # for phrase queries
  tag_fields: [] #  maybe add core attributes?
  timestamp_field: timestamp
  index_field_presence: true # For exists queries

search_settings:
  default_search_fields: []

