version: 0.9

template_id: datadog

index_id_patterns:
  - datadog*

description: Index config template for the datadog cloudprem indexes

priority: 0

# TODO: increase commit_timeout_secs of 5 secs after testing phase
indexing_settings:
  commit_timeout_secs: 5

# TODO: replace ALL default tokenizer with ddg tokenizer
# There would be two tokenizers: ddg and ddg_ignore_case (for message and all)

# There is an additional truncation in fields that applies only to indexed logs: the value is truncated to 75 KiB for the message field and 25 KiB for non-message fields.
# Datadog still stores the full text, and it remains visible in regular list queries in the Logs Explorer. However, the truncated version will be displayed when performing
# a grouped query, such as when grouping logs by that truncated field or performing similar operations that display that specific field.
# => FF tokenizer truncation after 75Kb for message and 25Kb for other fields (seems quite high)

# Sources:
# https://datadoghq.atlassian.net/wiki/spaces/LB/pages/2484928615/Logs+payload+format
# https://github.com/DataDog/logs-backend/blob/prod/domains/event-platform/libs/percolation/src/main/resources/elasticsearch/mappings/event.conf
# https://github.com/DataDog/logs-backend/blob/prod/domains/event-platform/libs/percolation/src/main/resources/elasticsearch/mappings/_root_event.conf
# https://github.com/DataDog/logs-backend/blob/prod/domains/event-platform/libs/facets/src/main/java/com/dd/logs/facets/RootFacets.java#L85
# Note that not all fields in the sources (e.g. event.conf) are handled here yet

# TODO Check following field names:
# tiebreaker(i64): used to differentiate logs with the same timestamp, which are stored only as ms. QW stores timestamp as ns. https://datadoghq.atlassian.net/wiki/spaces/LB/pages/1885536545/FAQ#I-sent-events-in-the-same-millisecond-but-with-a-timestamp-attribute-with-different-nanoseconds.-All-the-events-are-mixed-up-in-the-explorer.-How-to-explain-this%3F
# host_id(u64): A number for the host_id. How is it generated? Is is required?
# random_draw(f64), source_fragment_id(string), trace_id_low(string)

doc_mapping:
  mode: dynamic
  field_mappings:
    # TODO: Add RFC3164
    # With the preprocessing in Pomsky, we can actually just use one
    - name: timestamp
      type: datetime
      fast: true
      input_formats:
        - rfc3339
        - iso8601
        - unix_timestamp
  # TODO: Check if discovery_timestamp is used anywhere, or if we can drop it after ingestion
    - name: discovery_timestamp
      type: datetime
      fast: false
      indexed: false
      input_formats:
        - unix_timestamp
        - rfc3339
        - iso8601

  # TODO: Deactivated for now, as it is not clear what it is used for
    - name: ingest_size_in_bytes
      type: u64
      fast: true
      indexed: false
      stored: false
    # TODO: Needs to be populated
    - name: tiebreaker
      type: i64
      fast: true
      indexed: false
      stored: true

    - name: message
      type: text
      tokenizer: default # +lowercase case insensitive search on message
      record: position
      fast: true

    # Seems to be used only internally, e.g. for paging and fetch_one
    - name: id
      type: text
      tokenizer: raw

    - name: custom
      type: json
      tokenizer: default
      record: position
      fast: true

    - name: tag # contains normalized tags, e.g {"env": "prod"}
      type: json
      tokenizer: default
      fast: true

    - name: tags # we can completely drop it and reconstruct it from tag
      type: 'array<text>'
      stored: true
      indexed: false
      fast: false

    # The subfiels are `message` and `stack`. Are there others?
    # If all fields are clear, we can convert to object.
    # TODO: This is unused currently in the Pomsky processing
    # We need to move errors from custom to its own field because the tokenization is different
    - name: error
      type: json
      tokenizer: default
      record: position
      fast: false # We can use custom.error for aggregations instead
      # downstream expects the error to be in custom.error, so we will store it only there
      stored: false

    # other text like core attributes
    - name: service
      type: text
      tokenizer: raw
      fast: true
    - name: source
      type: text
      tokenizer: raw
      fast: true
    - name: service_type
      type: text
      tokenizer: raw
      fast: true
    - name: status
      type: text
      tokenizer: raw
      fast: true
    - name: host
      type: text
      tokenizer: raw
      fast: true
    - name: trace_id
      type: text
      tokenizer: raw
      fast: true
    - name: span_id
      type: text
      tokenizer: raw


   # TODO: normally there is an `sds_info` object. Check OP SDS scanner:
   # https://docs.datadoghq.com/observability_pipelines/processors/sensitive_data_scanner

    # default fields to search.
    - name: default
      type: concatenate
      concatenate_fields:
      - message
      - error
      tokenizer: default
      record: position # for phrase queries

    - name: all # ALL fields for *:search
      type: concatenate
      concatenate_fields: # This should contain all fields above
      # - timestamp # Not supported in concat fields
      - message
      # TODO: Check if we need to cover queries addressing tags, e.g. tags `*:"env:prod"` or tag `*:prod`
      # Generally this could be extracted by a query processor
      # - tag OR tags
      - error
      - source
      - service
      - service_type
      - status
      - host
      - trace_id
      - span_id
      - custom
      tokenizer: default # +lowercase insensitive
      record: position # for phrase queries

  tag_fields: [] #  maybe add core attributes?
  timestamp_field: timestamp
  index_field_presence: true # For exists queries

search_settings:
  default_search_fields: []

