ALTER TABLE indexes ALTER COLUMN index_uid TYPE VARCHAR(64);
ALTER TABLE indexes ALTER COLUMN index_id TYPE VARCHAR(50);
ALTER TABLE splits ALTER COLUMN index_uid TYPE VARCHAR(64);
ALTER TABLE delete_tasks ALTER COLUMN index_uid TYPE VARCHAR(64);
