ALTER TABLE indexes ALTER COLUMN index_uid TYPE VARCHAR(282);
ALTER TABLE indexes ALTER COLUMN index_id TYPE VARCHAR(255);
ALTER TABLE splits ALTER COLUMN index_uid TYPE VARCHAR(282);
ALTER TABLE delete_tasks ALTER COLUMN index_uid TYPE VARCHAR(282);
