[package]
name = "quickwit-remote-api"
description = "REST API server hitting a remote cluster"

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "remote-api"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
arrow = { workspace = true }
async-trait = { workspace = true }
bytesize = { workspace = true }
clap = { workspace = true , features = ["derive"]}
hyper-util = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
urlencoding = { workspace = true }
warp = { workspace = true }

quickwit-common = { workspace = true }
quickwit-config = { workspace = true }
quickwit-jaeger = { workspace = true }
quickwit-proto = { workspace = true }
quickwit-search = { workspace = true }
quickwit-serve = { workspace = true }

[build-dependencies]

[dev-dependencies]

[features]
