syntax = "proto3";

package cloudprem;

option go_package = "github.com/DataDog/dd-source/domains/event-platform/shared/libs/cloudprem-proto";
option java_package = "com.dd.event_platform.cloudprem.proto";

// We voluntarily avoid the multiple files option:
// Java does not make it possible to alias classnames, or import a package.
// We want to have a way to qualify the protobuf object class
// in a non ambiguous way. The static class will help with this.
option java_multiple_files = false;
option java_outer_classname = "CloudPremProto";

import "google/protobuf/any.proto";

service CloudPremService {
  rpc Ping(PingRequest) returns (PingResponse);
  rpc List(ListRequest) returns (ListResponse);
  rpc FetchOne(FetchOneRequest) returns (FetchOneResponse);
}

message PingRequest {}

message PingResponse {}

message ListRequest {
  google.protobuf.Any query = 1;
  uint32 num_events_to_fetch = 2;
  bool should_compute_count = 3;
  repeated string columns = 4;
  repeated SortKV sort = 5;
}

message SortKV {
  bool ascending = 1;
  string name = 2;
  string path = 3;
}

message ListResponse {
  uint64 count = 1;
  repeated Stream streams = 2;
  Statistics statistics = 3;
}

message Statistics {
  uint64 hit_count = 1;
  uint64 scanned_count = 2;
  uint64 result_memory_size = 3;
  uint64 max_result_memory_size = 4;
}

message Stream {
  repeated Event events = 1;
}

message Event {
  EventTracker tracker = 1;
  string content_json = 2;
}

message EventTracker {
  // A unique id tied to the event.
  string id = 1;

  // The epoch in milliseconds marking when the event was created.
  uint64 epoch_ms = 2;

  // An extra int to break ties.
  uint32 tiebreaker = 3;

  optional string fragment_id = 4;

  optional sint64 row_number = 5;
}

message FetchOneRequest {}

message FetchOneResponse {}
