// Adapted from
// https://github.com/tikv/rust-prometheus/blob/master/proto/proto_model.proto

syntax = "proto3";

option go_package = "github.com/DataDog/dd-source/domains/event-platform/shared/libs/cloudprem-proto";
option java_package = "com.dd.event_platform.cloudprem.proto";

package cloudprem.metrics;

message Label {
  string name  = 1;
  string value = 2;
}

message Gauge {
  double value = 1;
}

message Counter {
  double value = 1;
}

message Histogram {
  uint64 sample_count = 1;
  double sample_sum   = 2;
  repeated HistogramBucket buckets = 3; // Ordered in increasing order of upper_bound, +Inf bucket is optional.
}

message HistogramBucket {
  uint64 cumulative_count = 1; // Cumulative in increasing order.
  double upper_bound = 2;      // Inclusive.
}

message Metric {
  repeated Label labels = 1;
  oneof metric_value {
    double     gauge = 2;
    uint64   counter = 3;
    Histogram histogram = 4;
  }
}

message MetricFamily {
  string name   = 1;
  string help   = 2;
  repeated Metric metrics = 3;
}
