{
 "title": "Quickwit Indexers",
 "tags": [
  "quickwit",
  "indexer"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(quickwit_write_bytes,namespace)"
    }
   },
   {
    "name": "index",
    "label": "Index",
    "query": {
     "query": "label_values(quickwit_write_bytes,index)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(quickwit_write_bytes, instance)"
    }
   },
   {
    "name": "quickwit_rate_interval",
    "label": "Rate interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Indexing throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(quickwit_indexing_processed_bytes{index=\"$index\", namespace=\"$namespace\", instance=~\"$instance\", docs_processed_status=\"valid\"}[$quickwit_rate_interval]))",
     "legendFormat": "{{docs_processed_status}}"
    }
   ]
  },
  {
   "title": "Documents throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix: docs/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(quickwit_indexing_processed_docs_total{index=\"$index\", namespace=\"$namespace\", instance=~\"$instance\", docs_processed_status=\"valid\"}[$quickwit_rate_interval])",
     "legendFormat": "{{docs_processed_status}}"
    }
   ]
  },
  {
   "title": "Indexing throughput",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(quickwit_indexing_processed_bytes{index=\"$index\", namespace=\"$namespace\", instance=~\"$instance\"}[$quickwit_rate_interval])",
     "legendFormat": "{{docs_processed_status}}"
    }
   ]
  },
  {
   "title": "Writes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(quickwit_write_bytes{index=\"$index\"}[$quickwit_rate_interval])",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Object storage transfer rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(quickwit_storage_object_storage_download_num_bytes{namespace=\"$namespace\", instance=~\"$instance\"}[$quickwit_rate_interval]))",
     "legendFormat": "Download bytes / sec"
    },
    {
     "expr": "rate(quickwit_storage_object_storage_upload_num_bytes[$__rate_interval])",
     "legendFormat": "Upload bytes / sec"
    }
   ]
  },
  {
   "title": "Indexed documents rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(docs_processed_status) (rate(quickwit_indexing_processed_docs_total{index=\"$index\", namespace=\"$namespace\", instance=~\"$instance\"}[$quickwit_rate_interval]))",
     "legendFormat": "{{docs_processed_status}}"
    }
   ]
  },
  {
   "title": "Allocated bytes to Quickwit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(quickwit_allocated_num_bytes{pod=\"indexer-0\"}[$quickwit_rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}