{
 "title": "Quickwit Ingesters",
 "tags": [ "quickwit" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(quickwit_ingest_shards,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "gRPC server request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(quickwit_ingest_grpc_requests_total{kind=\"server\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC server request latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, rpc) (rate(quickwit_ingest_grpc_request_duration_seconds_bucket{kind=\"server\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC server in-flight requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "quickwit_ingest_grpc_requests_in_flight{kind=\"server\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shard status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(quickwit_ingest_shards{state=\"open\", instance=~\"$instance\"})",
     "legendFormat": "Open shards"
    },
    {
     "expr": "sum(quickwit_ingest_shards{state=\"closed\", instance=~\"$instance\"})",
     "legendFormat": "Closed shards"
    }
   ]
  },
  {
   "title": "WAL usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "quickwit_ingest_wal_disk_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "quickwit_ingest_wal_memory_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}