{
 "title": "Quickwit Metastore",
 "tags": [
  "quickwit",
  "metastore"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(quickwit_metastore_grpc_requests_total{kind=\"server\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Metastore requests rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(rpc) (rate(quickwit_metastore_grpc_requests_total{kind=\"server\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Metastore requests duration (p95)",
   "type": "timeseries",
   "description": "Duration in seconds",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, rpc) (rate(quickwit_metastore_grpc_request_duration_seconds_bucket{kind=\"server\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{rpc}}"
    }
   ]
  },
  {
   "title": "Metastore requests error rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(rpc) (rate(quickwit_metastore_grpc_requests_total{kind=\"server\", status=\"error\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{rpc}}"
    }
   ]
  }
 ]
}