metadata:
  name: cp-cloudprem
  namespace: logs-cloudprem
  type: egress_acl
  apiVersion: v1
spec:
  rules:
  - name: "lambda-api"
    service_accounts:
    - name: "cloudprem"
      namespace: "logs-cloudprem"
    domains:
      allowlist:
      - exact: "lambda.us-east-1.amazonaws.com:443"
      - exact: "datad0g.com:443"
      - suffix: .datad0g.com:443
      - suffix: .datadoghq.com:443
