name: "Build Quickwit binary for macOS"
description: "Build React app and Rust binary for macOS with cargo build."
inputs:
  target:
    description: "Target"
    required: true
  version:
    description: "Binary version"
    required: true
  token:
    description: "GitHub access token"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "ASSET_FULL_NAME=quickwit-${{ inputs.version }}-${{ inputs.target }}" >> $GITHUB_ENV
      shell: bash
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: "yarn"
        cache-dependency-path: quickwit/quickwit-ui/yarn.lock
    - run: make build-ui
      shell: bash
    - name: Install protoc
      run: brew install protobuf
      shell: bash
    - uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        targets: ${{ inputs.target }}
    - name: Add target aarch64-apple-darwin
      if: "${{ inputs.target == 'aarch64-apple-darwin' }}"
      run: rustup target add aarch64-apple-darwin
      shell: bash
      working-directory: ./quickwit
    - name: Retrieve and export commit date, hash, and tags
      run: |
          echo "QW_COMMIT_DATE=$(TZ=UTC0 git log -1 --format=%cd --date=format-local:%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
          echo "QW_COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "QW_COMMIT_TAGS=$(git tag --points-at HEAD | tr '\n' ',')" >> $GITHUB_ENV
      shell: bash
    - name: Build binary
      run: cargo build --release --features release-macos-feature-vendored-set --target ${{ matrix.target }}
      shell: bash
      working-directory: ./quickwit
      env:
        QW_COMMIT_DATE: ${{ env.QW_COMMIT_DATE }}
        QW_COMMIT_HASH: ${{ env.QW_COMMIT_HASH }}
        QW_COMMIT_TAGS: ${{ env.QW_COMMIT_TAGS }}
    - name: Bundle archive
      run: |
        make archive BINARY_FILE=quickwit/target/${{ inputs.target }}/release/quickwit \
          BINARY_VERSION=${{ inputs.version }} ARCHIVE_NAME=${{ env.ASSET_FULL_NAME }}
      shell: bash
    - name: Save binary archive for three days
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ASSET_FULL_NAME }}.tar.gz
        path: ./${{ env.ASSET_FULL_NAME }}.tar.gz
        retention-days: 3
    - name: Deploy archive to GitHub release
      if: "${{ inputs.version != 'nightly' }}"
      uses: quickwit-inc/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        file: ${{ env.ASSET_FULL_NAME }}.tar.gz
        overwrite: true
        tag_name: ${{ inputs.version }}
