// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Label {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Histogram {
    #[prost(uint64, tag = "1")]
    pub sample_count: u64,
    #[prost(double, tag = "2")]
    pub sample_sum: f64,
    /// Ordered in increasing order of upper_bound, +Inf bucket is optional.
    #[prost(message, repeated, tag = "3")]
    pub buckets: ::prost::alloc::vec::Vec<HistogramBucket>,
}
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HistogramBucket {
    /// Cumulative in increasing order.
    #[prost(uint64, tag = "1")]
    pub cumulative_count: u64,
    /// Inclusive.
    #[prost(double, tag = "2")]
    pub upper_bound: f64,
}
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Metric {
    #[prost(message, repeated, tag = "1")]
    pub labels: ::prost::alloc::vec::Vec<Label>,
    #[prost(oneof = "metric::MetricValue", tags = "2, 3, 4")]
    pub metric_value: ::core::option::Option<metric::MetricValue>,
}
/// Nested message and enum types in `Metric`.
pub mod metric {
    #[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
    #[serde(rename_all = "snake_case")]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum MetricValue {
        #[prost(double, tag = "2")]
        Gauge(f64),
        #[prost(uint64, tag = "3")]
        Counter(u64),
        #[prost(message, tag = "4")]
        Histogram(super::Histogram),
    }
}
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetricFamily {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub metrics: ::prost::alloc::vec::Vec<Metric>,
}
