// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetDebugInfoRequest {
    /// Restricts the debug info to the given roles.
    #[prost(string, repeated, tag = "1")]
    pub roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetDebugInfoResponse {
    #[prost(bytes = "bytes", tag = "1")]
    pub debug_info_json: ::prost::bytes::Bytes,
}
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PullMetricsRequest {}
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PullMetricsResponse {
    #[prost(message, repeated, tag = "1")]
    pub metric_families: ::prost::alloc::vec::Vec<
        super::super::cloudprem::metrics::MetricFamily,
    >,
}
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetNodeDiagnosticsRequest {}
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetNodeDiagnosticsResponse {
    #[prost(string, tag = "1")]
    pub build_info_json: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub runtime_info_json: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub node_config_json: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub env_info_json: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub deployment_info_json: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetNodeLogLevelRequest {
    /// tracing_subscriber EnvFilter directive, e.g. "quickwit=debug,tantivy=warn"
    #[prost(string, tag = "1")]
    pub filter: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetNodeLogLevelResponse {}
/// BEGIN quickwit-codegen
#[allow(unused_imports)]
use std::str::FromStr;
use tower::{Layer, Service, ServiceExt};
use quickwit_common::tower::RpcName;
impl RpcName for GetDebugInfoRequest {
    fn rpc_name() -> &'static str {
        "get_debug_info"
    }
}
impl RpcName for PullMetricsRequest {
    fn rpc_name() -> &'static str {
        "pull_metrics"
    }
}
impl RpcName for GetNodeDiagnosticsRequest {
    fn rpc_name() -> &'static str {
        "get_node_diagnostics"
    }
}
impl RpcName for SetNodeLogLevelRequest {
    fn rpc_name() -> &'static str {
        "set_node_log_level"
    }
}
#[cfg_attr(any(test, feature = "testsuite"), mockall::automock)]
#[async_trait::async_trait]
pub trait DeveloperService: std::fmt::Debug + Send + Sync + 'static {
    async fn get_debug_info(
        &self,
        request: GetDebugInfoRequest,
    ) -> crate::developer::DeveloperResult<GetDebugInfoResponse>;
    async fn pull_metrics(
        &self,
        request: PullMetricsRequest,
    ) -> crate::developer::DeveloperResult<PullMetricsResponse>;
    async fn get_node_diagnostics(
        &self,
        request: GetNodeDiagnosticsRequest,
    ) -> crate::developer::DeveloperResult<GetNodeDiagnosticsResponse>;
    async fn set_node_log_level(
        &self,
        request: SetNodeLogLevelRequest,
    ) -> crate::developer::DeveloperResult<SetNodeLogLevelResponse>;
}
#[derive(Debug, Clone)]
pub struct DeveloperServiceClient {
    inner: InnerDeveloperServiceClient,
}
#[derive(Debug, Clone)]
struct InnerDeveloperServiceClient(std::sync::Arc<dyn DeveloperService>);
impl DeveloperServiceClient {
    pub fn new<T>(instance: T) -> Self
    where
        T: DeveloperService,
    {
        #[cfg(any(test, feature = "testsuite"))]
        assert!(
            std::any::TypeId::of:: < T > () != std::any::TypeId::of:: <
            MockDeveloperService > (),
            "`MockDeveloperService` must be wrapped in a `MockDeveloperServiceWrapper`: use `DeveloperServiceClient::from_mock(mock)` to instantiate the client"
        );
        Self {
            inner: InnerDeveloperServiceClient(std::sync::Arc::new(instance)),
        }
    }
    pub fn as_grpc_service(
        &self,
        max_message_size: bytesize::ByteSize,
    ) -> developer_service_grpc_server::DeveloperServiceGrpcServer<
        DeveloperServiceGrpcServerAdapter,
    > {
        let adapter = DeveloperServiceGrpcServerAdapter::new(self.clone());
        developer_service_grpc_server::DeveloperServiceGrpcServer::new(adapter)
            .accept_compressed(tonic::codec::CompressionEncoding::Gzip)
            .accept_compressed(tonic::codec::CompressionEncoding::Zstd)
            .send_compressed(tonic::codec::CompressionEncoding::Gzip)
            .send_compressed(tonic::codec::CompressionEncoding::Zstd)
            .max_decoding_message_size(max_message_size.0 as usize)
            .max_encoding_message_size(max_message_size.0 as usize)
    }
    pub fn from_channel(
        addr: std::net::SocketAddr,
        channel: tonic::transport::Channel,
        max_message_size: bytesize::ByteSize,
        compression_encoding_opt: Option<tonic::codec::CompressionEncoding>,
    ) -> Self {
        let (_, connection_keys_watcher) = tokio::sync::watch::channel(
            std::collections::HashSet::from_iter([addr]),
        );
        let mut client = developer_service_grpc_client::DeveloperServiceGrpcClient::new(
                channel,
            )
            .max_decoding_message_size(max_message_size.0 as usize)
            .max_encoding_message_size(max_message_size.0 as usize);
        if let Some(compression_encoding) = compression_encoding_opt {
            client = client
                .accept_compressed(compression_encoding)
                .send_compressed(compression_encoding);
        }
        let adapter = DeveloperServiceGrpcClientAdapter::new(
            client,
            connection_keys_watcher,
        );
        Self::new(adapter)
    }
    pub fn from_balance_channel(
        balance_channel: quickwit_common::tower::BalanceChannel<std::net::SocketAddr>,
        max_message_size: bytesize::ByteSize,
        compression_encoding_opt: Option<tonic::codec::CompressionEncoding>,
    ) -> DeveloperServiceClient {
        let connection_keys_watcher = balance_channel.connection_keys_watcher();
        let mut client = developer_service_grpc_client::DeveloperServiceGrpcClient::new(
                balance_channel,
            )
            .max_decoding_message_size(max_message_size.0 as usize)
            .max_encoding_message_size(max_message_size.0 as usize);
        if let Some(compression_encoding) = compression_encoding_opt {
            client = client
                .accept_compressed(compression_encoding)
                .send_compressed(compression_encoding);
        }
        let adapter = DeveloperServiceGrpcClientAdapter::new(
            client,
            connection_keys_watcher,
        );
        Self::new(adapter)
    }
    pub fn from_mailbox<A>(mailbox: quickwit_actors::Mailbox<A>) -> Self
    where
        A: quickwit_actors::Actor + std::fmt::Debug + Send + 'static,
        DeveloperServiceMailbox<A>: DeveloperService,
    {
        DeveloperServiceClient::new(DeveloperServiceMailbox::new(mailbox))
    }
    pub fn tower() -> DeveloperServiceTowerLayerStack {
        DeveloperServiceTowerLayerStack::default()
    }
    #[cfg(any(test, feature = "testsuite"))]
    pub fn from_mock(mock: MockDeveloperService) -> Self {
        let mock_wrapper = mock_developer_service::MockDeveloperServiceWrapper {
            inner: tokio::sync::Mutex::new(mock),
        };
        Self::new(mock_wrapper)
    }
    #[cfg(any(test, feature = "testsuite"))]
    pub fn mocked() -> Self {
        Self::from_mock(MockDeveloperService::new())
    }
}
#[async_trait::async_trait]
impl DeveloperService for DeveloperServiceClient {
    #[tracing::instrument(skip_all, name = "developer.get_debug_info")]
    async fn get_debug_info(
        &self,
        request: GetDebugInfoRequest,
    ) -> crate::developer::DeveloperResult<GetDebugInfoResponse> {
        self.inner.0.get_debug_info(request).await
    }
    #[tracing::instrument(skip_all, name = "developer.pull_metrics")]
    async fn pull_metrics(
        &self,
        request: PullMetricsRequest,
    ) -> crate::developer::DeveloperResult<PullMetricsResponse> {
        self.inner.0.pull_metrics(request).await
    }
    #[tracing::instrument(skip_all, name = "developer.get_node_diagnostics")]
    async fn get_node_diagnostics(
        &self,
        request: GetNodeDiagnosticsRequest,
    ) -> crate::developer::DeveloperResult<GetNodeDiagnosticsResponse> {
        self.inner.0.get_node_diagnostics(request).await
    }
    #[tracing::instrument(skip_all, name = "developer.set_node_log_level")]
    async fn set_node_log_level(
        &self,
        request: SetNodeLogLevelRequest,
    ) -> crate::developer::DeveloperResult<SetNodeLogLevelResponse> {
        self.inner.0.set_node_log_level(request).await
    }
}
#[cfg(any(test, feature = "testsuite"))]
pub mod mock_developer_service {
    use super::*;
    #[derive(Debug)]
    pub struct MockDeveloperServiceWrapper {
        pub(super) inner: tokio::sync::Mutex<MockDeveloperService>,
    }
    #[async_trait::async_trait]
    impl DeveloperService for MockDeveloperServiceWrapper {
        async fn get_debug_info(
            &self,
            request: super::GetDebugInfoRequest,
        ) -> crate::developer::DeveloperResult<super::GetDebugInfoResponse> {
            self.inner.lock().await.get_debug_info(request).await
        }
        async fn pull_metrics(
            &self,
            request: super::PullMetricsRequest,
        ) -> crate::developer::DeveloperResult<super::PullMetricsResponse> {
            self.inner.lock().await.pull_metrics(request).await
        }
        async fn get_node_diagnostics(
            &self,
            request: super::GetNodeDiagnosticsRequest,
        ) -> crate::developer::DeveloperResult<super::GetNodeDiagnosticsResponse> {
            self.inner.lock().await.get_node_diagnostics(request).await
        }
        async fn set_node_log_level(
            &self,
            request: super::SetNodeLogLevelRequest,
        ) -> crate::developer::DeveloperResult<super::SetNodeLogLevelResponse> {
            self.inner.lock().await.set_node_log_level(request).await
        }
    }
}
pub type BoxFuture<T, E> = std::pin::Pin<
    Box<dyn std::future::Future<Output = Result<T, E>> + Send + 'static>,
>;
impl tower::Service<GetDebugInfoRequest> for InnerDeveloperServiceClient {
    type Response = GetDebugInfoResponse;
    type Error = crate::developer::DeveloperError;
    type Future = BoxFuture<Self::Response, Self::Error>;
    fn poll_ready(
        &mut self,
        _cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Result<(), Self::Error>> {
        std::task::Poll::Ready(Ok(()))
    }
    fn call(&mut self, request: GetDebugInfoRequest) -> Self::Future {
        let svc = self.clone();
        let fut = async move { svc.0.get_debug_info(request).await };
        Box::pin(fut)
    }
}
impl tower::Service<PullMetricsRequest> for InnerDeveloperServiceClient {
    type Response = PullMetricsResponse;
    type Error = crate::developer::DeveloperError;
    type Future = BoxFuture<Self::Response, Self::Error>;
    fn poll_ready(
        &mut self,
        _cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Result<(), Self::Error>> {
        std::task::Poll::Ready(Ok(()))
    }
    fn call(&mut self, request: PullMetricsRequest) -> Self::Future {
        let svc = self.clone();
        let fut = async move { svc.0.pull_metrics(request).await };
        Box::pin(fut)
    }
}
impl tower::Service<GetNodeDiagnosticsRequest> for InnerDeveloperServiceClient {
    type Response = GetNodeDiagnosticsResponse;
    type Error = crate::developer::DeveloperError;
    type Future = BoxFuture<Self::Response, Self::Error>;
    fn poll_ready(
        &mut self,
        _cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Result<(), Self::Error>> {
        std::task::Poll::Ready(Ok(()))
    }
    fn call(&mut self, request: GetNodeDiagnosticsRequest) -> Self::Future {
        let svc = self.clone();
        let fut = async move { svc.0.get_node_diagnostics(request).await };
        Box::pin(fut)
    }
}
impl tower::Service<SetNodeLogLevelRequest> for InnerDeveloperServiceClient {
    type Response = SetNodeLogLevelResponse;
    type Error = crate::developer::DeveloperError;
    type Future = BoxFuture<Self::Response, Self::Error>;
    fn poll_ready(
        &mut self,
        _cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Result<(), Self::Error>> {
        std::task::Poll::Ready(Ok(()))
    }
    fn call(&mut self, request: SetNodeLogLevelRequest) -> Self::Future {
        let svc = self.clone();
        let fut = async move { svc.0.set_node_log_level(request).await };
        Box::pin(fut)
    }
}
/// A tower service stack is a set of tower services.
#[derive(Debug)]
struct DeveloperServiceTowerServiceStack {
    #[allow(dead_code)]
    inner: InnerDeveloperServiceClient,
    get_debug_info_svc: quickwit_common::tower::BoxService<
        GetDebugInfoRequest,
        GetDebugInfoResponse,
        crate::developer::DeveloperError,
    >,
    pull_metrics_svc: quickwit_common::tower::BoxService<
        PullMetricsRequest,
        PullMetricsResponse,
        crate::developer::DeveloperError,
    >,
    get_node_diagnostics_svc: quickwit_common::tower::BoxService<
        GetNodeDiagnosticsRequest,
        GetNodeDiagnosticsResponse,
        crate::developer::DeveloperError,
    >,
    set_node_log_level_svc: quickwit_common::tower::BoxService<
        SetNodeLogLevelRequest,
        SetNodeLogLevelResponse,
        crate::developer::DeveloperError,
    >,
}
#[async_trait::async_trait]
impl DeveloperService for DeveloperServiceTowerServiceStack {
    async fn get_debug_info(
        &self,
        request: GetDebugInfoRequest,
    ) -> crate::developer::DeveloperResult<GetDebugInfoResponse> {
        self.get_debug_info_svc.clone().ready().await?.call(request).await
    }
    async fn pull_metrics(
        &self,
        request: PullMetricsRequest,
    ) -> crate::developer::DeveloperResult<PullMetricsResponse> {
        self.pull_metrics_svc.clone().ready().await?.call(request).await
    }
    async fn get_node_diagnostics(
        &self,
        request: GetNodeDiagnosticsRequest,
    ) -> crate::developer::DeveloperResult<GetNodeDiagnosticsResponse> {
        self.get_node_diagnostics_svc.clone().ready().await?.call(request).await
    }
    async fn set_node_log_level(
        &self,
        request: SetNodeLogLevelRequest,
    ) -> crate::developer::DeveloperResult<SetNodeLogLevelResponse> {
        self.set_node_log_level_svc.clone().ready().await?.call(request).await
    }
}
type GetDebugInfoLayer = quickwit_common::tower::BoxLayer<
    quickwit_common::tower::BoxService<
        GetDebugInfoRequest,
        GetDebugInfoResponse,
        crate::developer::DeveloperError,
    >,
    GetDebugInfoRequest,
    GetDebugInfoResponse,
    crate::developer::DeveloperError,
>;
type PullMetricsLayer = quickwit_common::tower::BoxLayer<
    quickwit_common::tower::BoxService<
        PullMetricsRequest,
        PullMetricsResponse,
        crate::developer::DeveloperError,
    >,
    PullMetricsRequest,
    PullMetricsResponse,
    crate::developer::DeveloperError,
>;
type GetNodeDiagnosticsLayer = quickwit_common::tower::BoxLayer<
    quickwit_common::tower::BoxService<
        GetNodeDiagnosticsRequest,
        GetNodeDiagnosticsResponse,
        crate::developer::DeveloperError,
    >,
    GetNodeDiagnosticsRequest,
    GetNodeDiagnosticsResponse,
    crate::developer::DeveloperError,
>;
type SetNodeLogLevelLayer = quickwit_common::tower::BoxLayer<
    quickwit_common::tower::BoxService<
        SetNodeLogLevelRequest,
        SetNodeLogLevelResponse,
        crate::developer::DeveloperError,
    >,
    SetNodeLogLevelRequest,
    SetNodeLogLevelResponse,
    crate::developer::DeveloperError,
>;
#[derive(Debug, Default)]
pub struct DeveloperServiceTowerLayerStack {
    get_debug_info_layers: Vec<GetDebugInfoLayer>,
    pull_metrics_layers: Vec<PullMetricsLayer>,
    get_node_diagnostics_layers: Vec<GetNodeDiagnosticsLayer>,
    set_node_log_level_layers: Vec<SetNodeLogLevelLayer>,
}
impl DeveloperServiceTowerLayerStack {
    pub fn stack_layer<L>(mut self, layer: L) -> Self
    where
        L: tower::Layer<
                quickwit_common::tower::BoxService<
                    GetDebugInfoRequest,
                    GetDebugInfoResponse,
                    crate::developer::DeveloperError,
                >,
            > + Clone + Send + Sync + 'static,
        <L as tower::Layer<
            quickwit_common::tower::BoxService<
                GetDebugInfoRequest,
                GetDebugInfoResponse,
                crate::developer::DeveloperError,
            >,
        >>::Service: tower::Service<
                GetDebugInfoRequest,
                Response = GetDebugInfoResponse,
                Error = crate::developer::DeveloperError,
            > + Clone + Send + Sync + 'static,
        <<L as tower::Layer<
            quickwit_common::tower::BoxService<
                GetDebugInfoRequest,
                GetDebugInfoResponse,
                crate::developer::DeveloperError,
            >,
        >>::Service as tower::Service<GetDebugInfoRequest>>::Future: Send + 'static,
        L: tower::Layer<
                quickwit_common::tower::BoxService<
                    PullMetricsRequest,
                    PullMetricsResponse,
                    crate::developer::DeveloperError,
                >,
            > + Clone + Send + Sync + 'static,
        <L as tower::Layer<
            quickwit_common::tower::BoxService<
                PullMetricsRequest,
                PullMetricsResponse,
                crate::developer::DeveloperError,
            >,
        >>::Service: tower::Service<
                PullMetricsRequest,
                Response = PullMetricsResponse,
                Error = crate::developer::DeveloperError,
            > + Clone + Send + Sync + 'static,
        <<L as tower::Layer<
            quickwit_common::tower::BoxService<
                PullMetricsRequest,
                PullMetricsResponse,
                crate::developer::DeveloperError,
            >,
        >>::Service as tower::Service<PullMetricsRequest>>::Future: Send + 'static,
        L: tower::Layer<
                quickwit_common::tower::BoxService<
                    GetNodeDiagnosticsRequest,
                    GetNodeDiagnosticsResponse,
                    crate::developer::DeveloperError,
                >,
            > + Clone + Send + Sync + 'static,
        <L as tower::Layer<
            quickwit_common::tower::BoxService<
                GetNodeDiagnosticsRequest,
                GetNodeDiagnosticsResponse,
                crate::developer::DeveloperError,
            >,
        >>::Service: tower::Service<
                GetNodeDiagnosticsRequest,
                Response = GetNodeDiagnosticsResponse,
                Error = crate::developer::DeveloperError,
            > + Clone + Send + Sync + 'static,
        <<L as tower::Layer<
            quickwit_common::tower::BoxService<
                GetNodeDiagnosticsRequest,
                GetNodeDiagnosticsResponse,
                crate::developer::DeveloperError,
            >,
        >>::Service as tower::Service<
            GetNodeDiagnosticsRequest,
        >>::Future: Send + 'static,
        L: tower::Layer<
                quickwit_common::tower::BoxService<
                    SetNodeLogLevelRequest,
                    SetNodeLogLevelResponse,
                    crate::developer::DeveloperError,
                >,
            > + Clone + Send + Sync + 'static,
        <L as tower::Layer<
            quickwit_common::tower::BoxService<
                SetNodeLogLevelRequest,
                SetNodeLogLevelResponse,
                crate::developer::DeveloperError,
            >,
        >>::Service: tower::Service<
                SetNodeLogLevelRequest,
                Response = SetNodeLogLevelResponse,
                Error = crate::developer::DeveloperError,
            > + Clone + Send + Sync + 'static,
        <<L as tower::Layer<
            quickwit_common::tower::BoxService<
                SetNodeLogLevelRequest,
                SetNodeLogLevelResponse,
                crate::developer::DeveloperError,
            >,
        >>::Service as tower::Service<SetNodeLogLevelRequest>>::Future: Send + 'static,
    {
        self.get_debug_info_layers
            .push(quickwit_common::tower::BoxLayer::new(layer.clone()));
        self.pull_metrics_layers
            .push(quickwit_common::tower::BoxLayer::new(layer.clone()));
        self.get_node_diagnostics_layers
            .push(quickwit_common::tower::BoxLayer::new(layer.clone()));
        self.set_node_log_level_layers
            .push(quickwit_common::tower::BoxLayer::new(layer.clone()));
        self
    }
    pub fn stack_get_debug_info_layer<L>(mut self, layer: L) -> Self
    where
        L: tower::Layer<
                quickwit_common::tower::BoxService<
                    GetDebugInfoRequest,
                    GetDebugInfoResponse,
                    crate::developer::DeveloperError,
                >,
            > + Send + Sync + 'static,
        L::Service: tower::Service<
                GetDebugInfoRequest,
                Response = GetDebugInfoResponse,
                Error = crate::developer::DeveloperError,
            > + Clone + Send + Sync + 'static,
        <L::Service as tower::Service<GetDebugInfoRequest>>::Future: Send + 'static,
    {
        self.get_debug_info_layers.push(quickwit_common::tower::BoxLayer::new(layer));
        self
    }
    pub fn stack_pull_metrics_layer<L>(mut self, layer: L) -> Self
    where
        L: tower::Layer<
                quickwit_common::tower::BoxService<
                    PullMetricsRequest,
                    PullMetricsResponse,
                    crate::developer::DeveloperError,
                >,
            > + Send + Sync + 'static,
        L::Service: tower::Service<
                PullMetricsRequest,
                Response = PullMetricsResponse,
                Error = crate::developer::DeveloperError,
            > + Clone + Send + Sync + 'static,
        <L::Service as tower::Service<PullMetricsRequest>>::Future: Send + 'static,
    {
        self.pull_metrics_layers.push(quickwit_common::tower::BoxLayer::new(layer));
        self
    }
    pub fn stack_get_node_diagnostics_layer<L>(mut self, layer: L) -> Self
    where
        L: tower::Layer<
                quickwit_common::tower::BoxService<
                    GetNodeDiagnosticsRequest,
                    GetNodeDiagnosticsResponse,
                    crate::developer::DeveloperError,
                >,
            > + Send + Sync + 'static,
        L::Service: tower::Service<
                GetNodeDiagnosticsRequest,
                Response = GetNodeDiagnosticsResponse,
                Error = crate::developer::DeveloperError,
            > + Clone + Send + Sync + 'static,
        <L::Service as tower::Service<
            GetNodeDiagnosticsRequest,
        >>::Future: Send + 'static,
    {
        self.get_node_diagnostics_layers
            .push(quickwit_common::tower::BoxLayer::new(layer));
        self
    }
    pub fn stack_set_node_log_level_layer<L>(mut self, layer: L) -> Self
    where
        L: tower::Layer<
                quickwit_common::tower::BoxService<
                    SetNodeLogLevelRequest,
                    SetNodeLogLevelResponse,
                    crate::developer::DeveloperError,
                >,
            > + Send + Sync + 'static,
        L::Service: tower::Service<
                SetNodeLogLevelRequest,
                Response = SetNodeLogLevelResponse,
                Error = crate::developer::DeveloperError,
            > + Clone + Send + Sync + 'static,
        <L::Service as tower::Service<SetNodeLogLevelRequest>>::Future: Send + 'static,
    {
        self.set_node_log_level_layers
            .push(quickwit_common::tower::BoxLayer::new(layer));
        self
    }
    pub fn build<T>(self, instance: T) -> DeveloperServiceClient
    where
        T: DeveloperService,
    {
        let inner_client = InnerDeveloperServiceClient(std::sync::Arc::new(instance));
        self.build_from_inner_client(inner_client)
    }
    pub fn build_from_channel(
        self,
        addr: std::net::SocketAddr,
        channel: tonic::transport::Channel,
        max_message_size: bytesize::ByteSize,
        compression_encoding_opt: Option<tonic::codec::CompressionEncoding>,
    ) -> DeveloperServiceClient {
        let client = DeveloperServiceClient::from_channel(
            addr,
            channel,
            max_message_size,
            compression_encoding_opt,
        );
        let inner_client = client.inner;
        self.build_from_inner_client(inner_client)
    }
    pub fn build_from_balance_channel(
        self,
        balance_channel: quickwit_common::tower::BalanceChannel<std::net::SocketAddr>,
        max_message_size: bytesize::ByteSize,
        compression_encoding_opt: Option<tonic::codec::CompressionEncoding>,
    ) -> DeveloperServiceClient {
        let client = DeveloperServiceClient::from_balance_channel(
            balance_channel,
            max_message_size,
            compression_encoding_opt,
        );
        let inner_client = client.inner;
        self.build_from_inner_client(inner_client)
    }
    pub fn build_from_mailbox<A>(
        self,
        mailbox: quickwit_actors::Mailbox<A>,
    ) -> DeveloperServiceClient
    where
        A: quickwit_actors::Actor + std::fmt::Debug + Send + 'static,
        DeveloperServiceMailbox<A>: DeveloperService,
    {
        let inner_client = InnerDeveloperServiceClient(
            std::sync::Arc::new(DeveloperServiceMailbox::new(mailbox)),
        );
        self.build_from_inner_client(inner_client)
    }
    #[cfg(any(test, feature = "testsuite"))]
    pub fn build_from_mock(self, mock: MockDeveloperService) -> DeveloperServiceClient {
        let client = DeveloperServiceClient::from_mock(mock);
        let inner_client = client.inner;
        self.build_from_inner_client(inner_client)
    }
    fn build_from_inner_client(
        self,
        inner_client: InnerDeveloperServiceClient,
    ) -> DeveloperServiceClient {
        let get_debug_info_svc = self
            .get_debug_info_layers
            .into_iter()
            .rev()
            .fold(
                quickwit_common::tower::BoxService::new(inner_client.clone()),
                |svc, layer| layer.layer(svc),
            );
        let pull_metrics_svc = self
            .pull_metrics_layers
            .into_iter()
            .rev()
            .fold(
                quickwit_common::tower::BoxService::new(inner_client.clone()),
                |svc, layer| layer.layer(svc),
            );
        let get_node_diagnostics_svc = self
            .get_node_diagnostics_layers
            .into_iter()
            .rev()
            .fold(
                quickwit_common::tower::BoxService::new(inner_client.clone()),
                |svc, layer| layer.layer(svc),
            );
        let set_node_log_level_svc = self
            .set_node_log_level_layers
            .into_iter()
            .rev()
            .fold(
                quickwit_common::tower::BoxService::new(inner_client.clone()),
                |svc, layer| layer.layer(svc),
            );
        let tower_svc_stack = DeveloperServiceTowerServiceStack {
            inner: inner_client,
            get_debug_info_svc,
            pull_metrics_svc,
            get_node_diagnostics_svc,
            set_node_log_level_svc,
        };
        DeveloperServiceClient::new(tower_svc_stack)
    }
}
#[derive(Debug, Clone)]
struct MailboxAdapter<A: quickwit_actors::Actor, E> {
    inner: quickwit_actors::Mailbox<A>,
    phantom: std::marker::PhantomData<E>,
}
impl<A, E> std::ops::Deref for MailboxAdapter<A, E>
where
    A: quickwit_actors::Actor,
{
    type Target = quickwit_actors::Mailbox<A>;
    fn deref(&self) -> &Self::Target {
        &self.inner
    }
}
#[derive(Debug)]
pub struct DeveloperServiceMailbox<A: quickwit_actors::Actor> {
    inner: MailboxAdapter<A, crate::developer::DeveloperError>,
}
impl<A: quickwit_actors::Actor> DeveloperServiceMailbox<A> {
    pub fn new(instance: quickwit_actors::Mailbox<A>) -> Self {
        let inner = MailboxAdapter {
            inner: instance,
            phantom: std::marker::PhantomData,
        };
        Self { inner }
    }
}
impl<A: quickwit_actors::Actor> Clone for DeveloperServiceMailbox<A> {
    fn clone(&self) -> Self {
        let inner = MailboxAdapter {
            inner: self.inner.clone(),
            phantom: std::marker::PhantomData,
        };
        Self { inner }
    }
}
impl<A, M, T, E> tower::Service<M> for DeveloperServiceMailbox<A>
where
    A: quickwit_actors::Actor
        + quickwit_actors::DeferableReplyHandler<M, Reply = Result<T, E>> + Send
        + 'static,
    M: std::fmt::Debug + Send + 'static,
    T: Send + 'static,
    E: std::fmt::Debug + Send + 'static,
    crate::developer::DeveloperError: From<quickwit_actors::AskError<E>>,
{
    type Response = T;
    type Error = crate::developer::DeveloperError;
    type Future = BoxFuture<Self::Response, Self::Error>;
    fn poll_ready(
        &mut self,
        _cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Result<(), Self::Error>> {
        //! This does not work with balance middlewares such as `tower::balance::pool::Pool` because
        //! this always returns `Poll::Ready`. The fix is to acquire a permit from the
        //! mailbox in `poll_ready` and consume it in `call`.
        std::task::Poll::Ready(Ok(()))
    }
    fn call(&mut self, message: M) -> Self::Future {
        let mailbox = self.inner.clone();
        let fut = async move {
            mailbox.ask_for_res(message).await.map_err(|error| error.into())
        };
        Box::pin(fut)
    }
}
#[async_trait::async_trait]
impl<A> DeveloperService for DeveloperServiceMailbox<A>
where
    A: quickwit_actors::Actor + std::fmt::Debug,
    DeveloperServiceMailbox<
        A,
    >: tower::Service<
            GetDebugInfoRequest,
            Response = GetDebugInfoResponse,
            Error = crate::developer::DeveloperError,
            Future = BoxFuture<GetDebugInfoResponse, crate::developer::DeveloperError>,
        >
        + tower::Service<
            PullMetricsRequest,
            Response = PullMetricsResponse,
            Error = crate::developer::DeveloperError,
            Future = BoxFuture<PullMetricsResponse, crate::developer::DeveloperError>,
        >
        + tower::Service<
            GetNodeDiagnosticsRequest,
            Response = GetNodeDiagnosticsResponse,
            Error = crate::developer::DeveloperError,
            Future = BoxFuture<
                GetNodeDiagnosticsResponse,
                crate::developer::DeveloperError,
            >,
        >
        + tower::Service<
            SetNodeLogLevelRequest,
            Response = SetNodeLogLevelResponse,
            Error = crate::developer::DeveloperError,
            Future = BoxFuture<SetNodeLogLevelResponse, crate::developer::DeveloperError>,
        >,
{
    async fn get_debug_info(
        &self,
        request: GetDebugInfoRequest,
    ) -> crate::developer::DeveloperResult<GetDebugInfoResponse> {
        self.clone().call(request).await
    }
    async fn pull_metrics(
        &self,
        request: PullMetricsRequest,
    ) -> crate::developer::DeveloperResult<PullMetricsResponse> {
        self.clone().call(request).await
    }
    async fn get_node_diagnostics(
        &self,
        request: GetNodeDiagnosticsRequest,
    ) -> crate::developer::DeveloperResult<GetNodeDiagnosticsResponse> {
        self.clone().call(request).await
    }
    async fn set_node_log_level(
        &self,
        request: SetNodeLogLevelRequest,
    ) -> crate::developer::DeveloperResult<SetNodeLogLevelResponse> {
        self.clone().call(request).await
    }
}
#[derive(Debug, Clone)]
pub struct DeveloperServiceGrpcClientAdapter<T> {
    inner: T,
    #[allow(dead_code)]
    connection_addrs_rx: tokio::sync::watch::Receiver<
        std::collections::HashSet<std::net::SocketAddr>,
    >,
}
impl<T> DeveloperServiceGrpcClientAdapter<T> {
    pub fn new(
        instance: T,
        connection_addrs_rx: tokio::sync::watch::Receiver<
            std::collections::HashSet<std::net::SocketAddr>,
        >,
    ) -> Self {
        Self {
            inner: instance,
            connection_addrs_rx,
        }
    }
}
#[async_trait::async_trait]
impl<T> DeveloperService
for DeveloperServiceGrpcClientAdapter<
    developer_service_grpc_client::DeveloperServiceGrpcClient<T>,
>
where
    T: tonic::client::GrpcService<tonic::body::Body> + std::fmt::Debug + Clone + Send
        + Sync + 'static,
    T::ResponseBody: tonic::codegen::Body<Data = tonic::codegen::Bytes> + Send + 'static,
    <T::ResponseBody as tonic::codegen::Body>::Error: Into<tonic::codegen::StdError>
        + Send,
    T::Future: Send,
{
    async fn get_debug_info(
        &self,
        request: GetDebugInfoRequest,
    ) -> crate::developer::DeveloperResult<GetDebugInfoResponse> {
        let mut tonic_request = tonic::Request::new(request);
        quickwit_common::tracing_utils::inject_current_context(
            tonic_request.metadata_mut(),
        );
        self.inner
            .clone()
            .get_debug_info(tonic_request)
            .await
            .map(|response| response.into_inner())
            .map_err(|status| crate::error::grpc_status_to_service_error(
                status,
                GetDebugInfoRequest::rpc_name(),
            ))
    }
    async fn pull_metrics(
        &self,
        request: PullMetricsRequest,
    ) -> crate::developer::DeveloperResult<PullMetricsResponse> {
        let mut tonic_request = tonic::Request::new(request);
        quickwit_common::tracing_utils::inject_current_context(
            tonic_request.metadata_mut(),
        );
        self.inner
            .clone()
            .pull_metrics(tonic_request)
            .await
            .map(|response| response.into_inner())
            .map_err(|status| crate::error::grpc_status_to_service_error(
                status,
                PullMetricsRequest::rpc_name(),
            ))
    }
    async fn get_node_diagnostics(
        &self,
        request: GetNodeDiagnosticsRequest,
    ) -> crate::developer::DeveloperResult<GetNodeDiagnosticsResponse> {
        let mut tonic_request = tonic::Request::new(request);
        quickwit_common::tracing_utils::inject_current_context(
            tonic_request.metadata_mut(),
        );
        self.inner
            .clone()
            .get_node_diagnostics(tonic_request)
            .await
            .map(|response| response.into_inner())
            .map_err(|status| crate::error::grpc_status_to_service_error(
                status,
                GetNodeDiagnosticsRequest::rpc_name(),
            ))
    }
    async fn set_node_log_level(
        &self,
        request: SetNodeLogLevelRequest,
    ) -> crate::developer::DeveloperResult<SetNodeLogLevelResponse> {
        let mut tonic_request = tonic::Request::new(request);
        quickwit_common::tracing_utils::inject_current_context(
            tonic_request.metadata_mut(),
        );
        self.inner
            .clone()
            .set_node_log_level(tonic_request)
            .await
            .map(|response| response.into_inner())
            .map_err(|status| crate::error::grpc_status_to_service_error(
                status,
                SetNodeLogLevelRequest::rpc_name(),
            ))
    }
}
#[derive(Debug)]
pub struct DeveloperServiceGrpcServerAdapter {
    inner: InnerDeveloperServiceClient,
}
impl DeveloperServiceGrpcServerAdapter {
    pub fn new<T>(instance: T) -> Self
    where
        T: DeveloperService,
    {
        Self {
            inner: InnerDeveloperServiceClient(std::sync::Arc::new(instance)),
        }
    }
}
#[async_trait::async_trait]
impl developer_service_grpc_server::DeveloperServiceGrpc
for DeveloperServiceGrpcServerAdapter {
    async fn get_debug_info(
        &self,
        tonic_request: tonic::Request<GetDebugInfoRequest>,
    ) -> Result<tonic::Response<GetDebugInfoResponse>, tonic::Status> {
        let parent_context = quickwit_common::tracing_utils::extract_context(
            tonic_request.metadata(),
        );
        let request = tonic_request.into_inner();
        let span = tracing::info_span!("developer.get_debug_info");
        let _ = <tracing::Span as tracing_opentelemetry::OpenTelemetrySpanExt>::set_parent(
            &span,
            parent_context,
        );
        let fut = async move {
            self.inner
                .0
                .get_debug_info(request)
                .await
                .map(tonic::Response::new)
                .map_err(crate::error::grpc_error_to_grpc_status)
        };
        <_ as tracing::Instrument>::instrument(fut, span).await
    }
    async fn pull_metrics(
        &self,
        tonic_request: tonic::Request<PullMetricsRequest>,
    ) -> Result<tonic::Response<PullMetricsResponse>, tonic::Status> {
        let parent_context = quickwit_common::tracing_utils::extract_context(
            tonic_request.metadata(),
        );
        let request = tonic_request.into_inner();
        let span = tracing::info_span!("developer.pull_metrics");
        let _ = <tracing::Span as tracing_opentelemetry::OpenTelemetrySpanExt>::set_parent(
            &span,
            parent_context,
        );
        let fut = async move {
            self.inner
                .0
                .pull_metrics(request)
                .await
                .map(tonic::Response::new)
                .map_err(crate::error::grpc_error_to_grpc_status)
        };
        <_ as tracing::Instrument>::instrument(fut, span).await
    }
    async fn get_node_diagnostics(
        &self,
        tonic_request: tonic::Request<GetNodeDiagnosticsRequest>,
    ) -> Result<tonic::Response<GetNodeDiagnosticsResponse>, tonic::Status> {
        let parent_context = quickwit_common::tracing_utils::extract_context(
            tonic_request.metadata(),
        );
        let request = tonic_request.into_inner();
        let span = tracing::info_span!("developer.get_node_diagnostics");
        let _ = <tracing::Span as tracing_opentelemetry::OpenTelemetrySpanExt>::set_parent(
            &span,
            parent_context,
        );
        let fut = async move {
            self.inner
                .0
                .get_node_diagnostics(request)
                .await
                .map(tonic::Response::new)
                .map_err(crate::error::grpc_error_to_grpc_status)
        };
        <_ as tracing::Instrument>::instrument(fut, span).await
    }
    async fn set_node_log_level(
        &self,
        tonic_request: tonic::Request<SetNodeLogLevelRequest>,
    ) -> Result<tonic::Response<SetNodeLogLevelResponse>, tonic::Status> {
        let parent_context = quickwit_common::tracing_utils::extract_context(
            tonic_request.metadata(),
        );
        let request = tonic_request.into_inner();
        let span = tracing::info_span!("developer.set_node_log_level");
        let _ = <tracing::Span as tracing_opentelemetry::OpenTelemetrySpanExt>::set_parent(
            &span,
            parent_context,
        );
        let fut = async move {
            self.inner
                .0
                .set_node_log_level(request)
                .await
                .map(tonic::Response::new)
                .map_err(crate::error::grpc_error_to_grpc_status)
        };
        <_ as tracing::Instrument>::instrument(fut, span).await
    }
}
/// Generated client implementations.
pub mod developer_service_grpc_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct DeveloperServiceGrpcClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl DeveloperServiceGrpcClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> DeveloperServiceGrpcClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> DeveloperServiceGrpcClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            DeveloperServiceGrpcClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_debug_info(
            &mut self,
            request: impl tonic::IntoRequest<super::GetDebugInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetDebugInfoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/quickwit.developer.DeveloperService/GetDebugInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "quickwit.developer.DeveloperService",
                        "GetDebugInfo",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn pull_metrics(
            &mut self,
            request: impl tonic::IntoRequest<super::PullMetricsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PullMetricsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/quickwit.developer.DeveloperService/PullMetrics",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("quickwit.developer.DeveloperService", "PullMetrics"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_node_diagnostics(
            &mut self,
            request: impl tonic::IntoRequest<super::GetNodeDiagnosticsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetNodeDiagnosticsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/quickwit.developer.DeveloperService/GetNodeDiagnostics",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "quickwit.developer.DeveloperService",
                        "GetNodeDiagnostics",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn set_node_log_level(
            &mut self,
            request: impl tonic::IntoRequest<super::SetNodeLogLevelRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetNodeLogLevelResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/quickwit.developer.DeveloperService/SetNodeLogLevel",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "quickwit.developer.DeveloperService",
                        "SetNodeLogLevel",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod developer_service_grpc_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with DeveloperServiceGrpcServer.
    #[async_trait]
    pub trait DeveloperServiceGrpc: std::marker::Send + std::marker::Sync + 'static {
        async fn get_debug_info(
            &self,
            request: tonic::Request<super::GetDebugInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetDebugInfoResponse>,
            tonic::Status,
        >;
        async fn pull_metrics(
            &self,
            request: tonic::Request<super::PullMetricsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PullMetricsResponse>,
            tonic::Status,
        >;
        async fn get_node_diagnostics(
            &self,
            request: tonic::Request<super::GetNodeDiagnosticsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetNodeDiagnosticsResponse>,
            tonic::Status,
        >;
        async fn set_node_log_level(
            &self,
            request: tonic::Request<super::SetNodeLogLevelRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetNodeLogLevelResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct DeveloperServiceGrpcServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> DeveloperServiceGrpcServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for DeveloperServiceGrpcServer<T>
    where
        T: DeveloperServiceGrpc,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/quickwit.developer.DeveloperService/GetDebugInfo" => {
                    #[allow(non_camel_case_types)]
                    struct GetDebugInfoSvc<T: DeveloperServiceGrpc>(pub Arc<T>);
                    impl<
                        T: DeveloperServiceGrpc,
                    > tonic::server::UnaryService<super::GetDebugInfoRequest>
                    for GetDebugInfoSvc<T> {
                        type Response = super::GetDebugInfoResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetDebugInfoRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DeveloperServiceGrpc>::get_debug_info(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetDebugInfoSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/quickwit.developer.DeveloperService/PullMetrics" => {
                    #[allow(non_camel_case_types)]
                    struct PullMetricsSvc<T: DeveloperServiceGrpc>(pub Arc<T>);
                    impl<
                        T: DeveloperServiceGrpc,
                    > tonic::server::UnaryService<super::PullMetricsRequest>
                    for PullMetricsSvc<T> {
                        type Response = super::PullMetricsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PullMetricsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DeveloperServiceGrpc>::pull_metrics(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PullMetricsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/quickwit.developer.DeveloperService/GetNodeDiagnostics" => {
                    #[allow(non_camel_case_types)]
                    struct GetNodeDiagnosticsSvc<T: DeveloperServiceGrpc>(pub Arc<T>);
                    impl<
                        T: DeveloperServiceGrpc,
                    > tonic::server::UnaryService<super::GetNodeDiagnosticsRequest>
                    for GetNodeDiagnosticsSvc<T> {
                        type Response = super::GetNodeDiagnosticsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetNodeDiagnosticsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DeveloperServiceGrpc>::get_node_diagnostics(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetNodeDiagnosticsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/quickwit.developer.DeveloperService/SetNodeLogLevel" => {
                    #[allow(non_camel_case_types)]
                    struct SetNodeLogLevelSvc<T: DeveloperServiceGrpc>(pub Arc<T>);
                    impl<
                        T: DeveloperServiceGrpc,
                    > tonic::server::UnaryService<super::SetNodeLogLevelRequest>
                    for SetNodeLogLevelSvc<T> {
                        type Response = super::SetNodeLogLevelResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetNodeLogLevelRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DeveloperServiceGrpc>::set_node_log_level(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetNodeLogLevelSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for DeveloperServiceGrpcServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "quickwit.developer.DeveloperService";
    impl<T> tonic::server::NamedService for DeveloperServiceGrpcServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
