/*
    Quickwit
    Copyright (C) 2021 Quickwit Inc.

    Quickwit is offered under the AGPL v3.0 and as commercial software.
    For commercial licensing, contact us at hello@quickwit.io.

    AGPL:
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

use anyhow::bail;
use quickwit_doc_mapping::{DocMapperType, build_doc_mapper};
use quickwit_metastore::{MetastoreUriResolver, SplitState};

// Holds index settings which we want to persist
pub struct IndexSettings {
    pub uri: String,
    pub sharding_field_name: Option<String>,
    pub doc_mapper_type: DocMapperType,
}

// TODO: remove that type
type IndexUri = String;

impl IndexSettings {
    /// Check if the doc mapper schema is consistent with the sharding field name
    fn validate(&self) -> anyhow::Result<()> {
        if let Some(sharding_field_name) = self.sharding_field_name.clone() {
            let schema = build_doc_mapper(self.doc_mapper_type.clone())
                .map(|mapper| mapper.schema())?;
            let result = schema.fields()
                .find(|(_, field_entry)| field_entry.name() == sharding_field_name);
            if result.is_none() {
                bail!("sharding field not present in doc mapper schema".to_string())
            } 
        }
        Ok(())
    }
}

// anyhow errors are fine for now but we'll want to move to a proper error type eventually.
pub async fn create_index(index_settings: IndexSettings) -> anyhow::Result<()> {
    // Validate here?
    index_settings.validate()?;
    // Udpate the metastore api so that it will persist index settings and
    // the index schema generated by the doc mapper
    let metastore = MetastoreUriResolver::default().resolve(&index_settings.uri)?;
    metastore.create_index(index_settings.uri, index_settings.doc_mapper_type).await?;
    Ok(())
}

// TODO
pub async fn index_data(index_uri: IndexUri) -> anyhow::Result<()> {
    let _metastore = MetastoreUriResolver::default().resolve(&index_uri)?;
    Ok(())
}

// TODO
pub async fn search_index(index_uri: IndexUri) -> anyhow::Result<()> {
    let metastore = MetastoreUriResolver::default().resolve(&index_uri)?;
    let _splits = metastore
        .list_splits(index_uri, SplitState::Published, None)
        .await?;
    Ok(())
}

pub async fn delete_index(index_uri: IndexUri) -> anyhow::Result<()> {
    let metastore = MetastoreUriResolver::default().resolve(&index_uri)?;
    metastore.delete_index(index_uri).await?;
    Ok(())
}

#[cfg(test)]
mod tests {

    #[test]
    fn test_create_index() -> anyhow::Result<()> {
        Ok(())
    }

    #[test]
    fn test_index_data() -> anyhow::Result<()> {
        Ok(())
    }

    #[test]
    fn test_search_index() -> anyhow::Result<()> {
        Ok(())
    }

    #[test]
    fn test_delete_index() -> anyhow::Result<()> {
        Ok(())
    }
}
