// This file is @generated by prost-build.
/// GetTraceParams represents the query for a single trace from the storage backend.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetTraceParams {
    /// trace_id is a 16 byte array containing the unique identifier for the trace to query.
    #[prost(bytes = "vec", tag = "1")]
    pub trace_id: ::prost::alloc::vec::Vec<u8>,
    /// start_time is the start of the time interval to search for the trace_id.
    ///
    /// This field is optional.
    #[prost(message, optional, tag = "2")]
    pub start_time: ::core::option::Option<::prost_types::Timestamp>,
    /// end_time is the end of the time interval to search for the trace_id.
    ///
    /// This field is optional.
    #[prost(message, optional, tag = "3")]
    pub end_time: ::core::option::Option<::prost_types::Timestamp>,
}
/// GetTracesRequest represents a request to retrieve multiple traces.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTracesRequest {
    #[prost(message, repeated, tag = "1")]
    pub query: ::prost::alloc::vec::Vec<GetTraceParams>,
}
/// GetServicesRequest represents a request to get service names.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetServicesRequest {}
/// GetServicesResponse represents the response for GetServicesRequest.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetServicesResponse {
    #[prost(string, repeated, tag = "1")]
    pub services: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// GetOperationsRequest represents a request to get operation names.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetOperationsRequest {
    /// service is the name of the service for which to get operation names.
    ///
    /// This field is required.
    #[prost(string, tag = "1")]
    pub service: ::prost::alloc::string::String,
    /// span_kind is the type of span which is used to distinguish between
    /// spans generated in a particular context.
    ///
    /// This field is optional.
    #[prost(string, tag = "2")]
    pub span_kind: ::prost::alloc::string::String,
}
/// Operation contains information about an operation for a given service.
#[derive(Ord, PartialOrd)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Operation {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub span_kind: ::prost::alloc::string::String,
}
/// GetOperationsResponse represents the response for GetOperationsRequest.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetOperationsResponse {
    #[prost(message, repeated, tag = "1")]
    pub operations: ::prost::alloc::vec::Vec<Operation>,
}
/// KeyValue and all its associated types are copied from opentelemetry-proto/common/v1/common.proto
/// (<https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/common/v1/common.proto>).
/// This type is used to store attributes in traces.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyValue {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<AnyValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnyValue {
    #[prost(oneof = "any_value::Value", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub value: ::core::option::Option<any_value::Value>,
}
/// Nested message and enum types in `AnyValue`.
pub mod any_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag = "1")]
        StringValue(::prost::alloc::string::String),
        #[prost(bool, tag = "2")]
        BoolValue(bool),
        #[prost(int64, tag = "3")]
        IntValue(i64),
        #[prost(double, tag = "4")]
        DoubleValue(f64),
        #[prost(message, tag = "5")]
        ArrayValue(super::ArrayValue),
        #[prost(message, tag = "6")]
        KvlistValue(super::KeyValueList),
        #[prost(bytes, tag = "7")]
        BytesValue(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyValueList {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<KeyValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ArrayValue {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<AnyValue>,
}
/// TraceQueryParameters contains query parameters to find traces. For a detailed
/// definition of each field in this message, refer to `TraceQueryParameters` in `jaeger.api_v3`
/// (<https://github.com/jaegertracing/jaeger-idl/blob/main/proto/api_v3/query_service.proto>).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TraceQueryParameters {
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub operation_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub attributes: ::prost::alloc::vec::Vec<KeyValue>,
    #[prost(message, optional, tag = "4")]
    pub start_time_min: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub start_time_max: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "6")]
    pub duration_min: ::core::option::Option<::prost_types::Duration>,
    #[prost(message, optional, tag = "7")]
    pub duration_max: ::core::option::Option<::prost_types::Duration>,
    #[prost(int32, tag = "8")]
    pub search_depth: i32,
}
/// FindTracesRequest represents a request to find traces.
/// It can be used to retrieve the traces (FindTraces) or simply
/// the trace IDs (FindTraceIDs).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FindTracesRequest {
    #[prost(message, optional, tag = "1")]
    pub query: ::core::option::Option<TraceQueryParameters>,
}
/// FoundTraceID is a wrapper around trace ID returned from FindTraceIDs
/// with an optional time range that may be used in GetTraces calls.
///
/// The time range is provided as an optimization hint for some storage backends
/// that can perform more efficient queries when they know the approximate time range.
/// The value should not be used for precise time-based filtering or assumptions.
/// It is meant as a rough boundary and may not be populated in all cases.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FoundTraceId {
    #[prost(bytes = "vec", tag = "1")]
    pub trace_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub start: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub end: ::core::option::Option<::prost_types::Timestamp>,
}
/// FindTraceIDsResponse represents the response for FindTracesRequest.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FindTraceIDsResponse {
    #[prost(message, repeated, tag = "1")]
    pub trace_ids: ::prost::alloc::vec::Vec<FoundTraceId>,
}
/// Generated client implementations.
pub mod trace_reader_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// TraceReader is a service that allows reading traces from storage.
    /// Note that if you implement this service, you should also implement
    /// OTEL's TraceService in package opentelemetry.proto.collector.trace.v1
    /// to allow pushing traces to the storage backend
    /// (<https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/collector/trace/v1/trace_service.proto>)
    #[derive(Debug, Clone)]
    pub struct TraceReaderClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl TraceReaderClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> TraceReaderClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> TraceReaderClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            TraceReaderClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// GetTraces returns a stream that retrieves all traces with given IDs.
        ///
        /// Chunking requirements:
        ///
        /// * A single TracesData chunk MUST NOT contain spans from multiple traces.
        /// * Large traces MAY be split across multiple, *consecutive* TracesData chunks.
        /// * Each returned TracesData object MUST NOT be empty.
        ///
        /// Edge cases:
        ///
        /// * If no spans are found for any given trace ID, the ID is ignored.
        /// * If none of the trace IDs are found in the storage, an empty response is returned.
        pub async fn get_traces(
            &mut self,
            request: impl tonic::IntoRequest<super::GetTracesRequest>,
        ) -> std::result::Result<
            tonic::Response<
                tonic::codec::Streaming<
                    super::super::super::super::opentelemetry::proto::trace::v1::TracesData,
                >,
            >,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/jaeger.storage.v2.TraceReader/GetTraces",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("jaeger.storage.v2.TraceReader", "GetTraces"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// GetServices returns all service names known to the backend from traces
        /// within its retention period.
        pub async fn get_services(
            &mut self,
            request: impl tonic::IntoRequest<super::GetServicesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetServicesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/jaeger.storage.v2.TraceReader/GetServices",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("jaeger.storage.v2.TraceReader", "GetServices"));
            self.inner.unary(req, path, codec).await
        }
        /// GetOperations returns all operation names for a given service
        /// known to the backend from traces within its retention period.
        pub async fn get_operations(
            &mut self,
            request: impl tonic::IntoRequest<super::GetOperationsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetOperationsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/jaeger.storage.v2.TraceReader/GetOperations",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("jaeger.storage.v2.TraceReader", "GetOperations"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// FindTraces returns a stream that retrieves traces matching query parameters.
        ///
        /// The chunking rules are the same as for GetTraces.
        ///
        /// If no matching traces are found, an empty stream is returned.
        pub async fn find_traces(
            &mut self,
            request: impl tonic::IntoRequest<super::FindTracesRequest>,
        ) -> std::result::Result<
            tonic::Response<
                tonic::codec::Streaming<
                    super::super::super::super::opentelemetry::proto::trace::v1::TracesData,
                >,
            >,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/jaeger.storage.v2.TraceReader/FindTraces",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("jaeger.storage.v2.TraceReader", "FindTraces"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// FindTraceIDs returns a stream that retrieves IDs of traces matching query parameters.
        ///
        /// If no matching traces are found, an empty stream is returned.
        ///
        /// This call behaves identically to FindTraces, except that it returns only the list
        /// of matching trace IDs. This is useful in some contexts, such as batch jobs, where a
        /// large list of trace IDs may be queried first and then the full traces are loaded
        /// in batches.
        pub async fn find_trace_i_ds(
            &mut self,
            request: impl tonic::IntoRequest<super::FindTracesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FindTraceIDsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/jaeger.storage.v2.TraceReader/FindTraceIDs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("jaeger.storage.v2.TraceReader", "FindTraceIDs"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod trace_reader_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with TraceReaderServer.
    #[async_trait]
    pub trait TraceReader: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the GetTraces method.
        type GetTracesStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<
                    super::super::super::super::opentelemetry::proto::trace::v1::TracesData,
                    tonic::Status,
                >,
            >
            + std::marker::Send
            + 'static;
        /// GetTraces returns a stream that retrieves all traces with given IDs.
        ///
        /// Chunking requirements:
        ///
        /// * A single TracesData chunk MUST NOT contain spans from multiple traces.
        /// * Large traces MAY be split across multiple, *consecutive* TracesData chunks.
        /// * Each returned TracesData object MUST NOT be empty.
        ///
        /// Edge cases:
        ///
        /// * If no spans are found for any given trace ID, the ID is ignored.
        /// * If none of the trace IDs are found in the storage, an empty response is returned.
        async fn get_traces(
            &self,
            request: tonic::Request<super::GetTracesRequest>,
        ) -> std::result::Result<tonic::Response<Self::GetTracesStream>, tonic::Status>;
        /// GetServices returns all service names known to the backend from traces
        /// within its retention period.
        async fn get_services(
            &self,
            request: tonic::Request<super::GetServicesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetServicesResponse>,
            tonic::Status,
        >;
        /// GetOperations returns all operation names for a given service
        /// known to the backend from traces within its retention period.
        async fn get_operations(
            &self,
            request: tonic::Request<super::GetOperationsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetOperationsResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the FindTraces method.
        type FindTracesStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<
                    super::super::super::super::opentelemetry::proto::trace::v1::TracesData,
                    tonic::Status,
                >,
            >
            + std::marker::Send
            + 'static;
        /// FindTraces returns a stream that retrieves traces matching query parameters.
        ///
        /// The chunking rules are the same as for GetTraces.
        ///
        /// If no matching traces are found, an empty stream is returned.
        async fn find_traces(
            &self,
            request: tonic::Request<super::FindTracesRequest>,
        ) -> std::result::Result<tonic::Response<Self::FindTracesStream>, tonic::Status>;
        /// FindTraceIDs returns a stream that retrieves IDs of traces matching query parameters.
        ///
        /// If no matching traces are found, an empty stream is returned.
        ///
        /// This call behaves identically to FindTraces, except that it returns only the list
        /// of matching trace IDs. This is useful in some contexts, such as batch jobs, where a
        /// large list of trace IDs may be queried first and then the full traces are loaded
        /// in batches.
        async fn find_trace_i_ds(
            &self,
            request: tonic::Request<super::FindTracesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FindTraceIDsResponse>,
            tonic::Status,
        >;
    }
    /// TraceReader is a service that allows reading traces from storage.
    /// Note that if you implement this service, you should also implement
    /// OTEL's TraceService in package opentelemetry.proto.collector.trace.v1
    /// to allow pushing traces to the storage backend
    /// (<https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/collector/trace/v1/trace_service.proto>)
    #[derive(Debug)]
    pub struct TraceReaderServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> TraceReaderServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for TraceReaderServer<T>
    where
        T: TraceReader,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/jaeger.storage.v2.TraceReader/GetTraces" => {
                    #[allow(non_camel_case_types)]
                    struct GetTracesSvc<T: TraceReader>(pub Arc<T>);
                    impl<
                        T: TraceReader,
                    > tonic::server::ServerStreamingService<super::GetTracesRequest>
                    for GetTracesSvc<T> {
                        type Response = super::super::super::super::opentelemetry::proto::trace::v1::TracesData;
                        type ResponseStream = T::GetTracesStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetTracesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TraceReader>::get_traces(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetTracesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/jaeger.storage.v2.TraceReader/GetServices" => {
                    #[allow(non_camel_case_types)]
                    struct GetServicesSvc<T: TraceReader>(pub Arc<T>);
                    impl<
                        T: TraceReader,
                    > tonic::server::UnaryService<super::GetServicesRequest>
                    for GetServicesSvc<T> {
                        type Response = super::GetServicesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetServicesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TraceReader>::get_services(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetServicesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/jaeger.storage.v2.TraceReader/GetOperations" => {
                    #[allow(non_camel_case_types)]
                    struct GetOperationsSvc<T: TraceReader>(pub Arc<T>);
                    impl<
                        T: TraceReader,
                    > tonic::server::UnaryService<super::GetOperationsRequest>
                    for GetOperationsSvc<T> {
                        type Response = super::GetOperationsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetOperationsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TraceReader>::get_operations(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetOperationsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/jaeger.storage.v2.TraceReader/FindTraces" => {
                    #[allow(non_camel_case_types)]
                    struct FindTracesSvc<T: TraceReader>(pub Arc<T>);
                    impl<
                        T: TraceReader,
                    > tonic::server::ServerStreamingService<super::FindTracesRequest>
                    for FindTracesSvc<T> {
                        type Response = super::super::super::super::opentelemetry::proto::trace::v1::TracesData;
                        type ResponseStream = T::FindTracesStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FindTracesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TraceReader>::find_traces(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FindTracesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/jaeger.storage.v2.TraceReader/FindTraceIDs" => {
                    #[allow(non_camel_case_types)]
                    struct FindTraceIDsSvc<T: TraceReader>(pub Arc<T>);
                    impl<
                        T: TraceReader,
                    > tonic::server::UnaryService<super::FindTracesRequest>
                    for FindTraceIDsSvc<T> {
                        type Response = super::FindTraceIDsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FindTracesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TraceReader>::find_trace_i_ds(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FindTraceIDsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for TraceReaderServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "jaeger.storage.v2.TraceReader";
    impl<T> tonic::server::NamedService for TraceReaderServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
