[package]
name = "quickwit-doc-transforms"
description = "Configure transforms on documents before indexing"

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
fnv = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
time = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
vrl = { workspace = true }

quickwit-common = { workspace = true }
quickwit-datetime = { workspace = true }

[dev-dependencies]
serde_yaml = { workspace = true }
env_logger = { workspace = true }

[features]
testsuite = []

[[bin]]
name = "convert_integrations"
path = "src/bin/convert_integrations.rs"
