// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Error {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub code: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageHeader {
    #[prost(enumeration = "MessageType", tag = "1")]
    pub r#type: i32,
    #[prost(enumeration = "MessageEncoding", tag = "2")]
    pub encoding: i32,
    /// used by process-client, see <https://datadoghq.atlassian.net/wiki/spaces/PROC/pages/2193294558/Process+Client>
    #[prost(uint32, tag = "3")]
    pub subscription_id: u32,
    #[prost(int32, tag = "4")]
    pub org_id: i32,
    /// The intake timestamp of the message
    /// This must be calculated as time.Now() at intake, the first time the message is seen.
    #[prost(int64, tag = "5")]
    pub timestamp: i64,
    /// an integer representation of the agent version. This is self reported via the agent via an HTTP header
    /// (X-Dd-Processagentversion) and encoded with VersionToUint32.
    #[prost(uint32, tag = "6")]
    pub agent_version: u32,
    /// The kafka partition number -- \[0, #partitioncount)  -- that the message was written to
    /// XXX it's not clear why this needs to be a header field and can't be inferred from the kafka message
    #[prost(uint32, tag = "7")]
    pub partition_id: u32,
    /// EventID is the Koutris event ID of the message, this will be set in process/network intake.
    #[prost(uint64, tag = "8")]
    pub event_id: u64,
    /// this acts as a hint to downstream services that message in question has container data.
    /// this was added in <https://github.com/DataDog/datadog-agent/pull/4180,> and will thus always
    /// be false in agents version 7.15 and below
    #[prost(bool, tag = "9")]
    pub has_containers: bool,
    /// The timestamp that the agent created the message
    /// this should theoretically be close to Timestamp, but can differ if the agent  has retried the message
    /// or the agent has NTP desync
    #[prost(int64, tag = "10")]
    pub agent_timestamp: i64,
    /// If this message was re-emitted from the agent due to a network or loadbalancer issue, this field captures which attempt
    /// the message succeeded with
    #[prost(uint32, tag = "11")]
    pub agent_attempts: u32,
    /// This is an opaque identifier that is used for tracing connection messages
    /// over multiple apps. See <https://datadoghq.atlassian.net/wiki/spaces/NET/pages/2580448137/RFC+Message+tracing+in+Networks+USM>
    #[prost(uint64, tag = "14")]
    pub pipeline_id: u64,
    /// These fields are set by network-resolver as hints to downstream consumers (network-stats-extractor, network-logger, network-dns-logger)
    /// that a message is safe to totally discard without any processing or decoding.
    #[prost(bool, tag = "12")]
    pub has_http_protocol_type: bool,
    #[prost(bool, tag = "13")]
    pub has_dns_connections: bool,
    #[prost(bool, tag = "15")]
    pub has_data_streams_type: bool,
    /// the agent start time as a unix timestamp (in seconds)
    #[prost(int64, tag = "17")]
    pub agent_start_time: i64,
    #[prost(bytes = "vec", tag = "18")]
    pub koutris_ng_trace_id: ::prost::alloc::vec::Vec<u8>,
    /// As part of the Event Platform intake migration, we need to continue to forward messages to the process_raw topic for network-container-writer, which will be the only remaining consumer from this topic.
    /// On the other hand, during the migration, process-resolver needs to drop these messages to avoid duplicate processing.
    /// This field will be set by an upstream service so that process-resolver can skip processing messages that were forwarded to process_raw for this purpose.
    /// See: <https://datadoghq.atlassian.net/wiki/spaces/CoMon/pages/5144576010/RFC+Processes+Pipeline+Intake+Deprecation#Network-Container-Writer>
    #[prost(bool, tag = "20")]
    pub forwarded_to_process_raw_for_networks: bool,
    /// This field is set by the agent to indicate whether live processes are enabled for the message.
    /// Starting from agent version 7.72.0, the process check can be used for other features such as service discovery.
    #[prost(bool, tag = "21")]
    pub live_processes_enabled: bool,
    /// required by event platform processes worker to parse hostname for downstream weak locality + filtering without decoding entire payload
    #[prost(string, tag = "22")]
    pub hostname: ::prost::alloc::string::String,
    /// see <https://github.com/DataDog/dd-go/pull/79953>
    #[prost(oneof = "message_header::ProcessesHints", tags = "16")]
    pub processes_hints: ::core::option::Option<message_header::ProcessesHints>,
    /// Slicer key used for sharding in the networks pipeline. Only set by network-intake
    /// see <https://github.com/DataDog/dd-go/pull/188218>
    #[prost(oneof = "message_header::SlicerMetadata", tags = "19")]
    pub slicer_metadata: ::core::option::Option<message_header::SlicerMetadata>,
}
/// Nested message and enum types in `MessageHeader`.
pub mod message_header {
    /// see <https://github.com/DataDog/dd-go/pull/79953>
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum ProcessesHints {
        #[prost(int32, tag = "16")]
        HintMask(i32),
    }
    /// Slicer key used for sharding in the networks pipeline. Only set by network-intake
    /// see <https://github.com/DataDog/dd-go/pull/188218>
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum SlicerMetadata {
        #[prost(uint64, tag = "19")]
        SlicerKey(u64),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Header {
    #[prost(message, optional, tag = "1")]
    pub auth: ::core::option::Option<Auth>,
    #[prost(int64, tag = "2")]
    pub timestamp: i64,
    #[prost(string, tag = "3")]
    pub id: ::prost::alloc::string::String,
    /// 4 is deprecated
    ///
    /// 6 is deprecated
    #[prost(message, optional, tag = "5")]
    pub error: ::core::option::Option<Error>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Auth {
    #[prost(int32, tag = "1")]
    pub permission: i32,
    /// Required to request Write-only permission
    #[prost(string, tag = "2")]
    pub api_key: ::prost::alloc::string::String,
    /// Required to request Read/Write permission
    #[prost(int32, tag = "3")]
    pub org_id: i32,
    #[prost(int32, tag = "4")]
    pub user_id: i32,
    #[prost(string, tag = "5")]
    pub session_token: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub token_version: i32,
    /// Validation tokens
    #[prost(string, tag = "7")]
    pub read_token: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub org_token: ::prost::alloc::string::String,
    /// Require to request Read-only permission
    #[prost(string, tag = "9")]
    pub application_key: ::prost::alloc::string::String,
    /// Client timestamp used when validation session tokens.
    #[prost(int32, tag = "10")]
    pub client_timestamp: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageEncoding {
    Protobuf = 0,
    Json = 1,
    ZstdPb = 2,
    ZlibPb = 3,
    Zstd1xPb = 4,
    ZstdPBxNoCgo = 5,
}
impl MessageEncoding {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Protobuf => "Protobuf",
            Self::Json => "JSON",
            Self::ZstdPb => "ZstdPB",
            Self::ZlibPb => "ZlibPB",
            Self::Zstd1xPb => "Zstd1xPB",
            Self::ZstdPBxNoCgo => "ZstdPBxNoCgo",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Protobuf" => Some(Self::Protobuf),
            "JSON" => Some(Self::Json),
            "ZstdPB" => Some(Self::ZstdPb),
            "ZlibPB" => Some(Self::ZlibPb),
            "Zstd1xPB" => Some(Self::Zstd1xPb),
            "ZstdPBxNoCgo" => Some(Self::ZstdPBxNoCgo),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageType {
    TypeReqInitAuth = 0,
    TypeResAuthAck = 1,
    TypeResInvalidAuth = 2,
    TypeReqSubscribe = 3,
    TypeReqUnsubscribe = 4,
    InvalidMessageType = 5,
    TypeAggrProcesses = 6,
    /// \[10, 11\] are deprecated (SQL Queries)
    TypeCollectorProc = 12,
    /// \[16, 21\] are deprecated (Saved Queries)
    TypeCollectorConnections = 22,
    TypeResCollector = 23,
    TypeCollectorReqStatus = 24,
    TypeCollectorRealTime = 27,
    TypeReqProcSummaryQuery = 28,
    TypeResProcSummaryQuery = 29,
    TypeReqContainerSummaryQuery = 36,
    TypeResContainerSummaryQuery = 37,
    TypeAggrContainers = 38,
    TypeCollectorContainer = 39,
    TypeCollectorContainerRealTime = 40,
    TypeCollectorPod = 41,
    TypeCollectorReplicaSet = 42,
    TypeCollectorDeployment = 43,
    TypeCollectorService = 44,
    TypeCollectorNode = 45,
    TypeCollectorCluster = 46,
    TypeCollectorJob = 47,
    TypeCollectorCronJob = 48,
    TypeCollectorDaemonSet = 49,
    TypeCollectorStatefulSet = 50,
    TypeCollectorPersistentVolume = 51,
    TypeCollectorPersistentVolumeClaim = 52,
    TypeCollectorProcDiscovery = 53,
    TypeCollectorRole = 54,
    TypeCollectorRoleBinding = 55,
    TypeCollectorClusterRole = 56,
    TypeCollectorClusterRoleBinding = 57,
    TypeCollectorServiceAccount = 58,
    TypeCollectorIngress = 59,
    TypeCollectorNamespace = 61,
    TypeCollectorManifest = 80,
    TypeCollectorManifestCrd = 81,
    TypeCollectorManifestCr = 82,
    TypeCollectorVerticalPodAutoscaler = 83,
    TypeCollectorHorizontalPodAutoscaler = 84,
    TypeCollectorNetworkPolicy = 85,
    TypeCollectorLimitRange = 86,
    TypeCollectorStorageClass = 87,
    TypeCollectorPodDisruptionBudget = 88,
    TypeCollectorKubeletConfiguration = 89,
    TypeCollectorEcsTask = 200,
}
impl MessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::TypeReqInitAuth => "TypeReqInitAuth",
            Self::TypeResAuthAck => "TypeResAuthAck",
            Self::TypeResInvalidAuth => "TypeResInvalidAuth",
            Self::TypeReqSubscribe => "TypeReqSubscribe",
            Self::TypeReqUnsubscribe => "TypeReqUnsubscribe",
            Self::InvalidMessageType => "InvalidMessageType",
            Self::TypeAggrProcesses => "TypeAggrProcesses",
            Self::TypeCollectorProc => "TypeCollectorProc",
            Self::TypeCollectorConnections => "TypeCollectorConnections",
            Self::TypeResCollector => "TypeResCollector",
            Self::TypeCollectorReqStatus => "TypeCollectorReqStatus",
            Self::TypeCollectorRealTime => "TypeCollectorRealTime",
            Self::TypeReqProcSummaryQuery => "TypeReqProcSummaryQuery",
            Self::TypeResProcSummaryQuery => "TypeResProcSummaryQuery",
            Self::TypeReqContainerSummaryQuery => "TypeReqContainerSummaryQuery",
            Self::TypeResContainerSummaryQuery => "TypeResContainerSummaryQuery",
            Self::TypeAggrContainers => "TypeAggrContainers",
            Self::TypeCollectorContainer => "TypeCollectorContainer",
            Self::TypeCollectorContainerRealTime => "TypeCollectorContainerRealTime",
            Self::TypeCollectorPod => "TypeCollectorPod",
            Self::TypeCollectorReplicaSet => "TypeCollectorReplicaSet",
            Self::TypeCollectorDeployment => "TypeCollectorDeployment",
            Self::TypeCollectorService => "TypeCollectorService",
            Self::TypeCollectorNode => "TypeCollectorNode",
            Self::TypeCollectorCluster => "TypeCollectorCluster",
            Self::TypeCollectorJob => "TypeCollectorJob",
            Self::TypeCollectorCronJob => "TypeCollectorCronJob",
            Self::TypeCollectorDaemonSet => "TypeCollectorDaemonSet",
            Self::TypeCollectorStatefulSet => "TypeCollectorStatefulSet",
            Self::TypeCollectorPersistentVolume => "TypeCollectorPersistentVolume",
            Self::TypeCollectorPersistentVolumeClaim => {
                "TypeCollectorPersistentVolumeClaim"
            }
            Self::TypeCollectorProcDiscovery => "TypeCollectorProcDiscovery",
            Self::TypeCollectorRole => "TypeCollectorRole",
            Self::TypeCollectorRoleBinding => "TypeCollectorRoleBinding",
            Self::TypeCollectorClusterRole => "TypeCollectorClusterRole",
            Self::TypeCollectorClusterRoleBinding => "TypeCollectorClusterRoleBinding",
            Self::TypeCollectorServiceAccount => "TypeCollectorServiceAccount",
            Self::TypeCollectorIngress => "TypeCollectorIngress",
            Self::TypeCollectorNamespace => "TypeCollectorNamespace",
            Self::TypeCollectorManifest => "TypeCollectorManifest",
            Self::TypeCollectorManifestCrd => "TypeCollectorManifestCRD",
            Self::TypeCollectorManifestCr => "TypeCollectorManifestCR",
            Self::TypeCollectorVerticalPodAutoscaler => {
                "TypeCollectorVerticalPodAutoscaler"
            }
            Self::TypeCollectorHorizontalPodAutoscaler => {
                "TypeCollectorHorizontalPodAutoscaler"
            }
            Self::TypeCollectorNetworkPolicy => "TypeCollectorNetworkPolicy",
            Self::TypeCollectorLimitRange => "TypeCollectorLimitRange",
            Self::TypeCollectorStorageClass => "TypeCollectorStorageClass",
            Self::TypeCollectorPodDisruptionBudget => "TypeCollectorPodDisruptionBudget",
            Self::TypeCollectorKubeletConfiguration => {
                "TypeCollectorKubeletConfiguration"
            }
            Self::TypeCollectorEcsTask => "TypeCollectorECSTask",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TypeReqInitAuth" => Some(Self::TypeReqInitAuth),
            "TypeResAuthAck" => Some(Self::TypeResAuthAck),
            "TypeResInvalidAuth" => Some(Self::TypeResInvalidAuth),
            "TypeReqSubscribe" => Some(Self::TypeReqSubscribe),
            "TypeReqUnsubscribe" => Some(Self::TypeReqUnsubscribe),
            "InvalidMessageType" => Some(Self::InvalidMessageType),
            "TypeAggrProcesses" => Some(Self::TypeAggrProcesses),
            "TypeCollectorProc" => Some(Self::TypeCollectorProc),
            "TypeCollectorConnections" => Some(Self::TypeCollectorConnections),
            "TypeResCollector" => Some(Self::TypeResCollector),
            "TypeCollectorReqStatus" => Some(Self::TypeCollectorReqStatus),
            "TypeCollectorRealTime" => Some(Self::TypeCollectorRealTime),
            "TypeReqProcSummaryQuery" => Some(Self::TypeReqProcSummaryQuery),
            "TypeResProcSummaryQuery" => Some(Self::TypeResProcSummaryQuery),
            "TypeReqContainerSummaryQuery" => Some(Self::TypeReqContainerSummaryQuery),
            "TypeResContainerSummaryQuery" => Some(Self::TypeResContainerSummaryQuery),
            "TypeAggrContainers" => Some(Self::TypeAggrContainers),
            "TypeCollectorContainer" => Some(Self::TypeCollectorContainer),
            "TypeCollectorContainerRealTime" => {
                Some(Self::TypeCollectorContainerRealTime)
            }
            "TypeCollectorPod" => Some(Self::TypeCollectorPod),
            "TypeCollectorReplicaSet" => Some(Self::TypeCollectorReplicaSet),
            "TypeCollectorDeployment" => Some(Self::TypeCollectorDeployment),
            "TypeCollectorService" => Some(Self::TypeCollectorService),
            "TypeCollectorNode" => Some(Self::TypeCollectorNode),
            "TypeCollectorCluster" => Some(Self::TypeCollectorCluster),
            "TypeCollectorJob" => Some(Self::TypeCollectorJob),
            "TypeCollectorCronJob" => Some(Self::TypeCollectorCronJob),
            "TypeCollectorDaemonSet" => Some(Self::TypeCollectorDaemonSet),
            "TypeCollectorStatefulSet" => Some(Self::TypeCollectorStatefulSet),
            "TypeCollectorPersistentVolume" => Some(Self::TypeCollectorPersistentVolume),
            "TypeCollectorPersistentVolumeClaim" => {
                Some(Self::TypeCollectorPersistentVolumeClaim)
            }
            "TypeCollectorProcDiscovery" => Some(Self::TypeCollectorProcDiscovery),
            "TypeCollectorRole" => Some(Self::TypeCollectorRole),
            "TypeCollectorRoleBinding" => Some(Self::TypeCollectorRoleBinding),
            "TypeCollectorClusterRole" => Some(Self::TypeCollectorClusterRole),
            "TypeCollectorClusterRoleBinding" => {
                Some(Self::TypeCollectorClusterRoleBinding)
            }
            "TypeCollectorServiceAccount" => Some(Self::TypeCollectorServiceAccount),
            "TypeCollectorIngress" => Some(Self::TypeCollectorIngress),
            "TypeCollectorNamespace" => Some(Self::TypeCollectorNamespace),
            "TypeCollectorManifest" => Some(Self::TypeCollectorManifest),
            "TypeCollectorManifestCRD" => Some(Self::TypeCollectorManifestCrd),
            "TypeCollectorManifestCR" => Some(Self::TypeCollectorManifestCr),
            "TypeCollectorVerticalPodAutoscaler" => {
                Some(Self::TypeCollectorVerticalPodAutoscaler)
            }
            "TypeCollectorHorizontalPodAutoscaler" => {
                Some(Self::TypeCollectorHorizontalPodAutoscaler)
            }
            "TypeCollectorNetworkPolicy" => Some(Self::TypeCollectorNetworkPolicy),
            "TypeCollectorLimitRange" => Some(Self::TypeCollectorLimitRange),
            "TypeCollectorStorageClass" => Some(Self::TypeCollectorStorageClass),
            "TypeCollectorPodDisruptionBudget" => {
                Some(Self::TypeCollectorPodDisruptionBudget)
            }
            "TypeCollectorKubeletConfiguration" => {
                Some(Self::TypeCollectorKubeletConfiguration)
            }
            "TypeCollectorECSTask" => Some(Self::TypeCollectorEcsTask),
            _ => None,
        }
    }
}
