name: Full test suite PR validation

on:
  pull_request:

permissions:
  contents: read

jobs:
  full-tests:
    name: Run full test suite
    uses: ./.github/workflows/full-tests.yml
    permissions:
      contents: read
      statuses: write
    with:
      head_sha: ${{ github.event.pull_request.head.sha }}
      merge_sha: ${{ github.sha }}
      pr_number: ${{ github.event.pull_request.number }}
