name: Publish custom cross images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "build/cross-images/**"

permissions:
  contents: read

jobs:
  build-cross-images:
    name: Publish cross images
    runs-on: ubuntu-latest
    environment:
        name: production
    steps:
      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Log in to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push cross images
        run: make cross-images
