name: dependency-scan

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

on:
  pull_request:
    paths:
      - '**'
      - '!lib/crates/**'
      - '!tests/**'
      - '!centreon-awie'
      - '!centreon-dsm'
      - '!centreon-ha'
      - '!centreon-open-tickets'
      - '!centreon'
      - '!php-tools'
      - '!cciam'
      - '!cloud-trial'
      - '!infrastructure'
      - '!license-delivery'
      - '!redis'
      - '!anomaly_detection/training/**'
      - '!centreon-cloud-ml/**'
      - '!runners/**'
      - '!.github/workflows/runners-build.yml'
      - '!backplane/**/*.tf'
      - '!.github/workflows/backplane.yml'
      - '!observability/**'
      - '!stonehenge/**'

  workflow_dispatch:

jobs:
  dependency-scan:
    uses: centreon/security-tools/.github/workflows/dependency-analysis.yml@main
