[overrides]
# rust-license-tool can't find the license for crunchy-0.2.2, but it's MIT
# according to the crate's Cargo.toml.
"crunchy-0.2.2" = { license = "MIT", origin = "https://github.com/eira-fransham/crunchy" }

# `ring` has a custom license that is mostly "ISC-style" but parts of it also fall under OpenSSL licensing.
"ring-0.17.8" = { license = "ISC AND Custom" }
